-- Resident contact correction workflow
-- Run this once in Supabase SQL Editor.

create table if not exists public.resident_change_requests (
  id bigint generated by default as identity primary key,
  resident_id bigint not null,
  existing_phone text,
  requested_phone text,
  existing_lives_in text,
  requested_lives_in text,
  request_note text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  submitted_by uuid default auth.uid(),
  submitted_at timestamptz not null default now(),
  reviewed_by uuid,
  reviewed_at timestamptz,
  review_note text
);

create index if not exists resident_change_requests_status_idx on public.resident_change_requests(status, submitted_at desc);
create index if not exists resident_change_requests_resident_idx on public.resident_change_requests(resident_id);

alter table public.resident_change_requests enable row level security;

-- Authenticated field users may submit requests and read their own requests.
drop policy if exists "authenticated users submit resident changes" on public.resident_change_requests;
create policy "authenticated users submit resident changes"
on public.resident_change_requests for insert
to authenticated
with check (submitted_by = auth.uid());

drop policy if exists "users read own resident changes" on public.resident_change_requests;
create policy "users read own resident changes"
on public.resident_change_requests for select
to authenticated
using (submitted_by = auth.uid());

-- Admin approval should be executed from an authenticated admin-only screen or secure server function.
-- This function applies only mobile and living-place corrections to public.campaign.
create or replace function public.approve_resident_change(request_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.resident_change_requests%rowtype;
begin
  select * into req
  from public.resident_change_requests
  where id = request_id and status = 'pending'
  for update;

  if not found then
    raise exception 'Pending request not found';
  end if;

  update public.campaign
  set phone = coalesce(req.requested_phone, phone),
      lives_in = coalesce(req.requested_lives_in, lives_in)
  where id = req.resident_id;

  update public.resident_change_requests
  set status = 'approved', reviewed_by = auth.uid(), reviewed_at = now()
  where id = request_id;
end;
$$;

revoke all on function public.approve_resident_change(bigint) from public;
-- Grant this function only to your real admin database role after role setup.
