const SUPABASE_URL='https://espezmdpkoixnfchomqb.supabase.co';
const SUPABASE_KEY='sb_publishable_xP8z74zcMuCkj6xlu1bJ3w_Kudqbcu1';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const state={residents:[],filter:'all',query:'',page:1,pageSize:30,selected:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const safe=v=>v==null?'':String(v), initials=n=>safe(n).trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'V';
const reached=r=>r.reach_status==='reached'||r.phone_status==='called'||['will-vote','not-vote'].includes(r.vote_status)||r.support_level==='guaranteed';
const needsCall=r=>r.phone_status==='need-call'||(!r.phone_status&&!reached(r));
const needsVisit=r=>!r.d2d_status||r.d2d_status==='not-visited';
const needsReview=r=>!r.vote_status||['pending','not-decided'].includes(r.vote_status);
const hasRemark=r=>Boolean(safe(r.remarks||r.remark||r.call_remarks||r.d2d_remarks).trim());
const pct=(done,total)=>total?Math.round(done/total*100):0;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2500)}
function setText(id,v){const el=$('#'+id);if(el)el.textContent=v}
function status(r){if(r.support_level==='guaranteed')return['confirmed','Guaranteed'];if(r.vote_status==='will-vote')return['confirmed','Will vote'];if(needsCall(r))return['pending','Need call'];if(needsVisit(r))return['pending','Need visit'];return['confirmed','Reached']}
function filtered(){const q=state.query.toLowerCase().trim();return state.residents.filter(r=>{const text=[r.name,r.national_id,r.house,r.official_address,r.lives_in,r.living_place,r.phone,r.mobile].map(safe).join(' ').toLowerCase();const ok={all:true,calls:needsCall(r),visits:needsVisit(r),reviews:needsReview(r),remarks:hasRemark(r)}[state.filter];return ok&&(!q||text.includes(q))})}
function updateDashboard(){const rows=state.residents,total=rows.length,calls=rows.filter(needsCall).length,visits=rows.filter(needsVisit).length,reviews=rows.filter(needsReview).length,remarks=rows.filter(hasRemark).length,reachedCount=rows.filter(reached).length;const rp=pct(reachedCount,total),cp=pct(total-calls,total),vp=pct(total-visits,total),dp=pct(total-reviews,total);setText('callsCount',calls.toLocaleString());setText('visitsCount',visits.toLocaleString());setText('reviewsCount',reviews.toLocaleString());setText('remarksCount',remarks.toLocaleString());setText('callsDetail',`${calls.toLocaleString()} residents waiting`);setText('visitsDetail',`${visits.toLocaleString()} homes unvisited`);setText('reviewsDetail',`${reviews.toLocaleString()} decisions pending`);setText('progressPercent',`${rp}%`);setText('healthTitle',rp>=70?'Steady progress':rp>=40?'Moving forward':'Needs attention');setText('healthText',`${reachedCount.toLocaleString()} of ${total.toLocaleString()} residents reached.`);[['calls',cp],['visits',vp],['vote',dp]].forEach(([k,v])=>{setText(k+'Percent',v+'%');setText(k+'BarText',v+'%');const bar=$('#'+k+'Bar');if(bar)bar.style.width=v+'%'});$('#progressRing').style.background=`conic-gradient(#82a78d 0 ${rp}%,#dce7de ${rp}% 100%)`;setText('databaseStatus',`Live · ${total.toLocaleString()} residents · campaign`)}
function render(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize;$('#residentList').innerHTML='';rows.slice(start,start+state.pageSize).forEach(r=>{const [cls,label]=status(r),card=document.createElement('article');card.className='resident-card';card.innerHTML=`<div class="resident-avatar">${initials(r.name)}</div><div class="resident-info"><b>${safe(r.name)||'Unnamed resident'}</b><small>${safe(r.national_id||r.id)} · ${safe(r.house||r.official_address||r.lives_in||'Address unavailable')}</small></div><span class="badge ${cls}">${label}</span>`;card.addEventListener('click',()=>openResident(r));card.addEventListener('pointermove',e=>{const b=card.getBoundingClientRect();card.style.transform=`perspective(700px) rotateX(${-(e.clientY-b.top-b.height/2)/35}deg) rotateY(${(e.clientX-b.left-b.width/2)/35}deg) translateY(-4px)`});card.addEventListener('pointerleave',()=>card.style.transform='');$('#residentList').appendChild(card)});if(!rows.length)$('#residentList').innerHTML='<div class="empty-state">No matching residents found.</div>';setText('pageInfo',`Page ${state.page} of ${pages} · ${rows.length.toLocaleString()} residents`);$('#prevPage').disabled=state.page===1;$('#nextPage').disabled=state.page===pages;setText('activeFilterLabel',({all:'Showing all residents',calls:'Showing residents needing calls',visits:'Showing homes needing door-to-door visits',reviews:'Showing vote decisions needing review',remarks:'Showing residents with remarks'})[state.filter])}
function applyFilter(filter){state.filter=filter;state.page=1;render();$('#residents').scrollIntoView({behavior:'smooth'});$('#filterButton').textContent=({all:'All residents',calls:'Need call',visits:'Door to door',reviews:'Vote review',remarks:'Remarks'})[filter];closeSearch()}
function openResident(r){state.selected=r;setText('modalAvatar',initials(r.name));setText('modalName',safe(r.name)||'Unnamed resident');setText('modalIdentity',`${safe(r.national_id||r.id)} · ${safe(r.house||r.official_address||r.lives_in||'Address unavailable')}`);$('#modalChips').innerHTML=[r.phone||r.mobile,r.sex,r.age?`Age ${r.age}`:'',r.party].filter(Boolean).map(x=>`<span>${safe(x)}</span>`).join('');$('#voteStatus').value=r.vote_status||'not-decided';$('#supportLevel').value=r.support_level||'not-guaranteed';$('#d2dStatus').value=r.d2d_status||'not-visited';$('#reachStatus').value=r.reach_status||'not-reached';$('#remarks').value=safe(r.remarks||r.remark||r.d2d_remarks||r.call_remarks);$('#residentModal').classList.add('open');$('#residentModal').setAttribute('aria-hidden','false')}
function closeResident(){state.selected=null;$('#residentModal').classList.remove('open');$('#residentModal').setAttribute('aria-hidden','true')}
async function saveResident(){if(!state.selected)return;const button=$('#saveResident'),payload={vote_status:$('#voteStatus').value,support_level:$('#supportLevel').value,d2d_status:$('#d2dStatus').value,reach_status:$('#reachStatus').value,remarks:$('#remarks').value.trim()};if(payload.vote_status==='will-vote'||payload.vote_status==='not-vote'||payload.support_level==='guaranteed'||payload.d2d_status==='reach')payload.reach_status='reached';button.disabled=true;button.textContent='Saving…';const {data,error}=await db.from('campaign').update(payload).eq('id',state.selected.id).select().single();button.disabled=false;button.textContent='Save resident update';if(error){console.error(error);toast(error.code==='42501'?'Sign in is required to edit residents':error.message);return}const i=state.residents.findIndex(x=>x.id===state.selected.id);state.residents[i]=data;updateDashboard();render();closeResident();toast('Resident update saved')}
async function load(){try{const all=[];for(let from=0;;from+=1000){const {data,error}=await db.from('campaign').select('*').order('id',{ascending:true}).range(from,from+999);if(error)throw error;all.push(...data);if(data.length<1000)break}state.residents=all;updateDashboard();render();toast(`${all.length.toLocaleString()} residents connected`)}catch(e){console.error(e);setText('databaseStatus','Database connection failed');$('#residentList').innerHTML=`<div class="empty-state"><b>Could not load campaign records.</b><br>${safe(e.message)}</div>`}}
$('#residentSearch').addEventListener('input',e=>{state.query=e.target.value;state.page=1;render()});$('#filterButton').addEventListener('click',()=>{const order=['all','calls','visits','reviews','remarks'];applyFilter(order[(order.indexOf(state.filter)+1)%order.length])});$('#prevPage').onclick=()=>{state.page--;render();$('#residents').scrollIntoView({behavior:'smooth'})};$('#nextPage').onclick=()=>{state.page++;render();$('#residents').scrollIntoView({behavior:'smooth'})};$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>applyFilter(b.dataset.filter)));$('#startWork').onclick=()=>applyFilter('calls');$('#openResidents').onclick=()=>applyFilter('all');$('#closeResident').onclick=closeResident;$('#cancelResident').onclick=closeResident;$('#saveResident').onclick=saveResident;$('#residentModal').onclick=e=>{if(e.target.id==='residentModal')closeResident()};
const command=$('#commandPalette'),globalSearch=$('#globalSearch');function openSearch(){command.classList.add('open');setTimeout(()=>globalSearch.focus(),30)}function closeSearch(){command.classList.remove('open')}$('#globalSearchButton').onclick=openSearch;$('#closeSearch').onclick=closeSearch;globalSearch.addEventListener('input',e=>{state.query=e.target.value;$('#residentSearch').value=e.target.value;render()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'){closeSearch();closeResident()}});$$('#mainNav button').forEach(b=>b.onclick=()=>{$$('#mainNav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.target)$('#'+b.dataset.target).scrollIntoView({behavior:'smooth'})});const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});$$('.reveal').forEach(el=>observer.observe(el));load();