/** @type {import('tailwindcss').Config} */
module.exports={
  content:['./app/**/*.{js,ts,jsx,tsx}','./components/**/*.{js,ts,jsx,tsx}','./layout/**/*.{js,ts,jsx,tsx}','./shared/**/*.{js,ts,jsx,tsx}','./lib/**/*.{js,ts,jsx,tsx}'],
  theme:{extend:{
    fontFamily:{sans:['Inter','system-ui','sans-serif']},
    colors:{
      primary:'var(--primary)',
      'primary-hover':'var(--primary-hover)',
      'primary-light':'var(--primary-light)',
      navy:'var(--navy)',
      body:'var(--body-text)',
      accent:'var(--accent-green)',
      canvas:'var(--background)',
      card:'var(--card)',
      border:'var(--border)',
      calm:{50:'var(--background)',100:'var(--primary-light)',500:'var(--body-text)',700:'var(--navy)',900:'var(--navy)'}
    },
    borderRadius:{card:'var(--radius-card)',pill:'var(--radius-pill)',input:'var(--radius-pill)'},
    boxShadow:{card:'var(--shadow-card)','card-hover':'var(--shadow-card-hover)',soft:'var(--shadow-card)',panel:'var(--shadow-card)'}
  }},
  plugins:[]
};