'use client';
import {useEffect,useMemo,useState} from 'react';
import {createWorkflowShare} from '../lib/operations';
import {getResidents,supabase} from '../lib/supabase';
import type {Resident} from '../lib/types';
import {PartyFilter,ResidentIdentity,matchesParty} from '../shared/ResidentIdentity';

type Assignment={id:number|string;resident_id:number|string;assignee_name:string;assignment_type:string;status:string;notes?:string|null;assigned_at?:string|null};
export default function AssignmentsContent(){
 const [residents,setResidents]=useState<Resident[]>([]),[items,setItems]=useState<Assignment[]>([]),[query,setQuery]=useState(''),[party,setParty]=useState('all'),[house,setHouse]=useState('all'),[box,setBox]=useState('all'),[assignee,setAssignee]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[creating,setCreating]=useState(false);
 async function load(){try{const [residentRows,response]=await Promise.all([getResidents(),supabase.from('assignments').select('*').order('assigned_at',{ascending:false}).limit(500)]);if(response.error)throw response.error;setResidents(residentRows);setItems((response.data||[]) as Assignment[])}catch(e){setError(e instanceof Error?e.message:'Unable to load assignments')}}useEffect(()=>{load()},[]);
 const houses=useMemo(()=>[...new Set(residents.map(r=>(r.house||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[residents]);
 const boxes=useMemo(()=>[...new Set(residents.map(r=>(r.election_box||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[residents]);
 const filteredResidents=useMemo(()=>residents.filter(r=>{const text=[r.name,r.national_id,r.phone,r.house,r.lives_in,r.election_box].join(' ').toLowerCase();return matchesParty(r,party)&&(house==='all'||r.house===house)&&(box==='all'||r.election_box===box)&&text.includes(query.toLowerCase())}),[residents,party,house,box,query]);
 const matches=filteredResidents.slice(0,30);
 const map=useMemo(()=>new Map(residents.map(r=>[String(r.id),r])),[residents]);
 const visibleItems=useMemo(()=>items.filter(i=>{const r=map.get(String(i.resident_id));return r?matchesParty(r,party):party==='all'}),[items,map,party]);
 async function assign(){if(!selected||!assignee.trim()){setError('Select a resident and enter an assignee.');return}setError('');const payload={id:Date.now(),resident_id:Number(selected),assignee_name:assignee.trim(),assignment_type:'general',status:'active',assigned_at:new Date().toISOString()};const {error}=await supabase.from('assignments').insert(payload);if(error){setError(error.message);return}setMessage('Resident assigned.');setAssignee('');setSelected('');load()}
 async function complete(item:Assignment){const {error}=await supabase.from('assignments').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',item.id);if(error)setError(error.message);else load()}
 async function createShare(openWhatsApp:boolean){if(!filteredResidents.length){setError('No residents match the current filters.');return}setCreating(true);setError('');try{const ids=filteredResidents.map(r=>Number(r.id));const filterLabel=[party!=='all'?party:null,house!=='all'?house:null,box!=='all'?`Box ${box}`:null,query.trim()?`Search: ${query.trim()}`:null].filter(Boolean).join(' · ')||'All matching residents';const result=await createWorkflowShare({workflow:'assignments',title:`Resident assignment · ${filterLabel}`,resident_ids:ids,can_update:true});const link=`${window.location.origin}/Vote/share/?token=${result.token}`;const text=`Please open this assignment list, enter your name, select the residents you will handle, and submit.\n\n${filterLabel}\n${ids.length} residents\n${link}`;if(openWhatsApp){window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}else{await navigator.clipboard.writeText(link);setMessage(`Assignment link copied for ${ids.length} filtered residents.`)}}catch(e){setError(e instanceof Error?e.message:'Share failed')}finally{setCreating(false)}}
 function clearFilters(){setQuery('');setParty('all');setHouse('all');setBox('all')}
 return <div className="space-y-4">
  <section className="page-hero"><p className="eyebrow">Field ownership</p><h1 className="mt-2">Assignments</h1><p className="mt-2 text-sm text-body">Filter residents, create a private assignment link, and send it through WhatsApp. The receiver enters their name, selects residents, and submits.</p><div className="mt-4"><PartyFilter value={party} onChange={setParty}/></div></section>
  <section className="panel"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[1fr_220px_200px_auto]"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, ID, mobile, address or box"/><select className="field" value={house} onChange={e=>setHouse(e.target.value)}><option value="all">All houses</option>{houses.map(item=><option key={item} value={item}>{item}</option>)}</select><select className="field" value={box} onChange={e=>setBox(e.target.value)}><option value="all">All election boxes</option>{boxes.map(item=><option key={item} value={item}>Box {item}</option>)}</select><button className="btn-secondary" onClick={clearFilters}>Reset</button></div><div className="mt-4 flex flex-col gap-3 rounded-xl border border-border bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-navy">{filteredResidents.length.toLocaleString()} residents in this share</b><p className="mt-1 text-xs text-body">Name, National ID, mobile, address and election box will be shown.</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={creating} onClick={()=>createShare(false)}>Copy assignment link</button><button className="btn-primary" disabled={creating} onClick={()=>createShare(true)}>{creating?'Creating…':'Send through WhatsApp'}</button></div></div>{message&&<p className="mt-3 text-sm font-semibold text-accent">{message}</p>}{error&&<div className="error-banner mt-3">{error}</div>}</section>
  <section className="panel"><div className="section-heading"><div><p className="eyebrow">Direct assignment</p><h2 className="mt-1">Assign one resident internally</h2></div></div><div className="grid gap-3 lg:grid-cols-[1fr_1fr_auto]"><div className="relative"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search resident"/>{query&&<div className="absolute z-20 mt-1 max-h-72 w-full overflow-y-auto rounded-xl border border-border bg-card shadow-card">{matches.map(r=><button key={String(r.id)} className="block w-full border-b border-border p-3 text-left hover:bg-primary-light" onClick={()=>{setSelected(String(r.id));setQuery(r.name||String(r.id))}}><ResidentIdentity resident={r} compact/></button>)}</div>}</div><input className="field" value={assignee} onChange={e=>setAssignee(e.target.value)} placeholder="Assignee name"/><button className="btn-primary" onClick={assign}>Assign resident</button></div></section>
  <section className="panel overflow-hidden p-0"><div className="divide-y divide-border">{visibleItems.map(item=>{const resident=map.get(String(item.resident_id));return <article key={String(item.id)} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div>{resident?<ResidentIdentity resident={resident}/>:<b>Resident {item.resident_id}</b>}<p className="mt-1 text-xs text-body">Assigned to {item.assignee_name}</p></div><div className="flex items-center gap-2"><span className="status-chip bg-primary-light text-body">{item.status}</span>{item.status==='active'&&<button className="btn-secondary" onClick={()=>complete(item)}>Complete</button>}</div></article>})}</div></section>
 </div>
}
