'use client';
import {useEffect,useMemo,useState} from 'react';
import {createWorkflowShare} from '../lib/operations';
import {getResidents,supabase} from '../lib/supabase';
import type {Resident} from '../lib/types';
import {PartyFilter,ResidentIdentity,matchesParty} from '../shared/ResidentIdentity';

type Assignment={id:number|string;resident_id:number|string;assignee_name:string;assignment_type:string;status:string;notes?:string|null;assigned_at?:string|null};
type ShareLink={id:number|string;token:string;title?:string|null;status_filter?:string|null;resident_ids?:number[]|null;active:boolean;created_at?:string|null};

export default function AssignmentsContent(){
 const [residents,setResidents]=useState<Resident[]>([]),[items,setItems]=useState<Assignment[]>([]),[links,setLinks]=useState<ShareLink[]>([]),[query,setQuery]=useState(''),[party,setParty]=useState('all'),[house,setHouse]=useState('all'),[box,setBox]=useState('all'),[linkAssignee,setLinkAssignee]=useState(''),[historyAssignee,setHistoryAssignee]=useState(''),[historySearch,setHistorySearch]=useState(''),[editingId,setEditingId]=useState<string|null>(null),[editingName,setEditingName]=useState(''),[editingLinkId,setEditingLinkId]=useState<string|null>(null),[editingLinkName,setEditingLinkName]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[creating,setCreating]=useState(false),[showAllResidents,setShowAllResidents]=useState(false);

 async function load(){try{setError('');const [residentRows,assignmentResponse,shareResponse]=await Promise.all([getResidents(),supabase.from('assignments').select('*').order('assigned_at',{ascending:false}).limit(2000),supabase.from('workflow_shares').select('*').eq('workflow','assignments').order('created_at',{ascending:false}).limit(300)]);if(assignmentResponse.error)throw assignmentResponse.error;if(shareResponse.error)throw shareResponse.error;setResidents(residentRows);setItems((assignmentResponse.data||[]) as Assignment[]);setLinks((shareResponse.data||[]) as ShareLink[])}catch(e){setError(e instanceof Error?e.message:'Unable to load assignments')}}
 useEffect(()=>{load()},[]);

 const houses=useMemo(()=>[...new Set(residents.map(r=>(r.house||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[residents]);
 const boxes=useMemo(()=>[...new Set(residents.map(r=>(r.election_box||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[residents]);
 const filteredResidents=useMemo(()=>residents.filter(r=>{const text=[r.name,r.national_id,r.phone,r.house,r.lives_in,r.election_box].join(' ').toLowerCase();return matchesParty(r,party)&&(house==='all'||r.house===house)&&(box==='all'||r.election_box===box)&&text.includes(query.toLowerCase())}),[residents,party,house,box,query]);
 const visibleResidents=filteredResidents.slice(0,showAllResidents?120:12);
 const residentMap=useMemo(()=>new Map(residents.map(r=>[String(r.id),r])),[residents]);
 const assignees=useMemo(()=>[...new Set(items.map(item=>item.assignee_name).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[items]);
 const currentLinks=useMemo(()=>{const latest=new Map<string,ShareLink>();for(const link of links){const key=(link.status_filter||'Unnamed assignee').trim().toLowerCase();if(!latest.has(key))latest.set(key,link)}return [...latest.values()]},[links]);
 useEffect(()=>{if(!historyAssignee&&assignees.length)setHistoryAssignee(assignees[0])},[assignees,historyAssignee]);
 useEffect(()=>{setShowAllResidents(false)},[query,party,house,box]);
 const selectedItems=useMemo(()=>items.filter(item=>{if(item.assignee_name!==historyAssignee)return false;const resident=residentMap.get(String(item.resident_id));const text=[resident?.name,resident?.national_id,resident?.phone,resident?.house,resident?.lives_in,item.assignee_name].join(' ').toLowerCase();return text.includes(historySearch.toLowerCase())}),[items,residentMap,historyAssignee,historySearch]);
 const shareUrl=(link:ShareLink)=>`${window.location.origin}/Vote/share/?token=${link.token}`;

 async function createShare(openWhatsApp:boolean){const assigneeName=linkAssignee.trim();if(!assigneeName){setError('Enter the assignee name before creating the link.');return}if(!filteredResidents.length){setError('No residents match the current filters.');return}setCreating(true);setError('');setMessage('');try{const oldLinks=links.filter(link=>link.active&&(link.status_filter||'').trim().toLowerCase()===assigneeName.toLowerCase());if(oldLinks.length){const shutdown=await supabase.from('workflow_shares').update({active:false}).in('id',oldLinks.map(link=>link.id));if(shutdown.error)throw shutdown.error}const ids=filteredResidents.map(r=>Number(r.id));const filterLabel=[party!=='all'?party:null,house!=='all'?house:null,box!=='all'?`Box ${box}`:null,query.trim()?`Search: ${query.trim()}`:null].filter(Boolean).join(' · ')||'All matching residents';const result=await createWorkflowShare({workflow:'assignments',title:`Assignment for ${assigneeName} · ${filterLabel}`,status_filter:assigneeName,resident_ids:ids,can_update:true});const link=`${window.location.origin}/Vote/share/?token=${result.token}`;const text=`Hello ${assigneeName}, please open your private assignment link and select the residents you will handle.\n\n${filterLabel}\n${ids.length} residents\n${link}`;if(openWhatsApp){window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}else{await navigator.clipboard.writeText(link);setMessage(`Current assignment link copied for ${assigneeName}.`)}await load()}catch(e){setError(e instanceof Error?e.message:'Share failed')}finally{setCreating(false)}}
 function clearFilters(){setQuery('');setParty('all');setHouse('all');setBox('all')}
 function chooseAssignee(name:string){setHistoryAssignee(name);setHistorySearch('');window.setTimeout(()=>document.getElementById('assignee-residents')?.scrollIntoView({behavior:'smooth',block:'start'}),50)}
 function beginEdit(item:Assignment){setEditingId(String(item.id));setEditingName(item.assignee_name)}
 async function saveEdit(item:Assignment){const name=editingName.trim();if(!name){setError('Assignee name cannot be empty.');return}const {error}=await supabase.from('assignments').update({assignee_name:name}).eq('id',item.id);if(error){setError(error.message);return}setEditingId(null);setEditingName('');setHistoryAssignee(name);setMessage('Assignment updated.');load()}
 async function remove(item:Assignment){const resident=residentMap.get(String(item.resident_id));if(!window.confirm(`Delete ${resident?.name||`resident ${item.resident_id}`} from ${item.assignee_name}'s assignments?`))return;const {error}=await supabase.from('assignments').delete().eq('id',item.id);if(error){setError(error.message);return}setMessage('Assignment deleted.');load()}
 function beginLinkEdit(link:ShareLink){setEditingLinkId(String(link.id));setEditingLinkName(link.status_filter||'')}
 async function saveLinkEdit(link:ShareLink){const name=editingLinkName.trim();if(!name){setError('Assignee name cannot be empty.');return}const duplicateIds=links.filter(item=>item.active&&String(item.id)!==String(link.id)&&(item.status_filter||'').trim().toLowerCase()===name.toLowerCase()).map(item=>item.id);if(duplicateIds.length){const shutdown=await supabase.from('workflow_shares').update({active:false}).in('id',duplicateIds);if(shutdown.error){setError(shutdown.error.message);return}}const suffix=(link.title||'').includes(' · ')?(link.title||'').split(' · ').slice(1).join(' · '):'Shared residents';const {error}=await supabase.from('workflow_shares').update({status_filter:name,title:`Assignment for ${name} · ${suffix}`}).eq('id',link.id);if(error){setError(error.message);return}setEditingLinkId(null);setEditingLinkName('');setMessage('Assignee name updated.');load()}
 async function setLinkActive(link:ShareLink,active:boolean){const label=link.status_filter||'this assignee';if(!window.confirm(`${active?'Enable':'Disable'} the assignment link for ${label}?`))return;const {error}=await supabase.from('workflow_shares').update({active}).eq('id',link.id);if(error){setError(error.message);return}setMessage(active?'Assignment link enabled.':'Assignment link disabled.');load()}
 async function copyLink(link:ShareLink){await navigator.clipboard.writeText(shareUrl(link));setMessage(`Link copied for ${link.status_filter||'assignee'}.`)}
 function sendLink(link:ShareLink){const name=link.status_filter||'assignee';const text=`Hello ${name}, please open your private assignment link.\n\n${(link.resident_ids||[]).length} residents\n${shareUrl(link)}`;window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}
 async function deleteAssignee(link:ShareLink){const name=(link.status_filter||'').trim();if(!window.confirm(`Permanently delete ${name||'this assignee'}, the share link, and all of their assignments? This cannot be undone.`))return;setError('');const assignmentDelete=name?await supabase.from('assignments').delete().eq('assignee_name',name):null;if(assignmentDelete?.error){setError(assignmentDelete.error.message);return}const linkDelete=await supabase.from('workflow_shares').delete().eq('id',link.id);if(linkDelete.error){setError(linkDelete.error.message);return}if(historyAssignee===name)setHistoryAssignee('');setMessage('Assignee and assignment link deleted.');load()}

 return <div className="space-y-4">
  <section className="page-hero"><p className="eyebrow">Field ownership</p><h1 className="mt-2">Assignments</h1><div className="mt-4"><PartyFilter value={party} onChange={setParty}/></div></section>

  <section className="panel">
   <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[240px_1fr_220px_200px_auto]"><div><label className="field-label">Assignee name</label><input className="field" value={linkAssignee} onChange={e=>setLinkAssignee(e.target.value)} placeholder="Enter assignee name"/></div><div><label className="field-label">Search residents</label><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, ID, mobile, address or box"/></div><div><label className="field-label">Official address</label><select className="field" value={house} onChange={e=>setHouse(e.target.value)}><option value="all">All houses</option>{houses.map(item=><option key={item} value={item}>{item}</option>)}</select></div><div><label className="field-label">Election box</label><select className="field" value={box} onChange={e=>setBox(e.target.value)}><option value="all">All election boxes</option>{boxes.map(item=><option key={item} value={item}>Box {item}</option>)}</select></div><div className="flex items-end"><button className="btn-secondary w-full" onClick={clearFilters}>Reset filters</button></div></div>
   <div className="mt-4 flex flex-col gap-3 rounded-xl border border-border bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><b className="text-navy">{filteredResidents.length.toLocaleString()} residents</b><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={creating} onClick={()=>createShare(false)}>Copy link</button><button className="btn-primary" disabled={creating} onClick={()=>createShare(true)}>{creating?'Creating…':'Send through WhatsApp'}</button></div></div>
   {message&&<p className="mt-3 text-sm font-semibold text-accent">{message}</p>}{error&&<div className="error-banner mt-3">{error}</div>}
  </section>

  <section className="panel overflow-hidden p-0">
   <div className="flex items-center justify-between gap-3 border-b border-border px-4 py-4 sm:px-5"><div><p className="eyebrow">Filtered residents</p><h2 className="mt-1">Residents in this link</h2><p className="mt-1 text-sm text-body">Showing {visibleResidents.length.toLocaleString()} of {filteredResidents.length.toLocaleString()}</p></div>{filteredResidents.length>12&&<button className="btn-secondary shrink-0" onClick={()=>setShowAllResidents(value=>!value)}>{showAllResidents?'Show 12':'Show more'}</button>}</div>
   <div className="max-h-[680px] overflow-y-auto p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visibleResidents.map(r=><article key={String(r.id)} className="soft-card self-start p-4"><ResidentIdentity resident={r}/><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><Info label="Resident ID" value={String(r.id)}/><Info label="Mobile" value={r.phone}/><Info label="Official address" value={r.house}/><Info label="Living place" value={r.lives_in}/><Info label="Election box" value={r.election_box}/></dl></article>)}</div>{!filteredResidents.length&&<div className="empty-state m-4">No residents match the current filters.</div>}</div>
  </section>

  <section className="panel"><div className="section-heading"><div><p className="eyebrow">Current links</p><h2 className="mt-1">One link per assignee</h2></div></div><div className="grid gap-3 md:grid-cols-2">{currentLinks.map(link=>{const editing=editingLinkId===String(link.id);return <article key={String(link.id)} className="rounded-2xl border border-border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><b className="text-navy">{link.status_filter||'Unnamed assignee'}</b><p className="mt-1 text-xs text-body">{(link.resident_ids||[]).length.toLocaleString()} residents</p><p className="mt-1 text-xs text-body">{link.created_at?new Date(link.created_at).toLocaleString():'Creation time unavailable'}</p></div><span className={`status-chip ${link.active?'status-success':'bg-slate-100 text-slate-500'}`}>{link.active?'Active':'Disabled'}</span></div>{editing?<div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input className="field" value={editingLinkName} onChange={e=>setEditingLinkName(e.target.value)} autoFocus/><button className="btn-primary" onClick={()=>saveLinkEdit(link)}>Save</button><button className="btn-secondary" onClick={()=>{setEditingLinkId(null);setEditingLinkName('')}}>Cancel</button></div>:<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3"><button className="btn-secondary" disabled={!link.active} onClick={()=>window.open(shareUrl(link),'_blank','noopener,noreferrer')}>Open</button><button className="btn-secondary" onClick={()=>copyLink(link)}>Copy</button><button className="btn-secondary" disabled={!link.active} onClick={()=>sendLink(link)}>WhatsApp</button><button className="btn-secondary" onClick={()=>beginLinkEdit(link)}>Edit</button>{link.active?<button className="btn-secondary" onClick={()=>setLinkActive(link,false)}>Disable</button>:<button className="btn-success" onClick={()=>setLinkActive(link,true)}>Enable</button>}<button className="btn-danger" onClick={()=>deleteAssignee(link)}>Delete</button></div>}</article>})}{!currentLinks.length&&<div className="empty-state md:col-span-2">No assignment links.</div>}</div></section>

  <section className="panel sticky top-0 z-10"><div className="grid gap-3 lg:grid-cols-[260px_1fr]"><div><label className="field-label">Show assignee</label><select className="field" value={historyAssignee} onChange={e=>chooseAssignee(e.target.value)}>{assignees.map(name=><option key={name} value={name}>{name}</option>)}</select></div><div><label className="field-label">Search residents</label><input className="field" value={historySearch} onChange={e=>setHistorySearch(e.target.value)} placeholder="Resident name, ID, mobile or address"/></div></div></section>

  {historyAssignee&&<section id="assignee-residents" className="panel scroll-mt-28 overflow-hidden p-0"><div className="flex items-center justify-between border-b border-border px-5 py-4"><h2>{historyAssignee}</h2><span className="status-chip bg-primary-light text-primary">{selectedItems.length} resident{selectedItems.length===1?'':'s'}</span></div><div className="max-h-[620px] divide-y divide-border overflow-y-auto">{selectedItems.slice(0,100).map(item=>{const resident=residentMap.get(String(item.resident_id)),editing=editingId===String(item.id);return <article key={String(item.id)} className="p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0 flex-1">{resident?<ResidentIdentity resident={resident}/>:<b>Resident {item.resident_id}</b>}</div>{editing?<div className="flex w-full flex-col gap-2 sm:flex-row lg:w-auto"><input className="field min-w-[220px]" value={editingName} onChange={e=>setEditingName(e.target.value)} autoFocus/><button className="btn-primary" onClick={()=>saveEdit(item)}>Save</button><button className="btn-secondary" onClick={()=>{setEditingId(null);setEditingName('')}}>Cancel</button></div>:<div className="flex gap-2"><button className="btn-secondary" onClick={()=>beginEdit(item)}>Modify</button><button className="btn-secondary text-danger" onClick={()=>remove(item)}>Delete</button></div>}</div></article>})}{!selectedItems.length&&<div className="empty-state m-4">No residents match.</div>}</div></section>}
 </div>
}

function Info({label,value}:{label:string;value?:string|null}){return <div className="rounded-xl bg-slate-50 px-3 py-2"><dt className="text-[10px] font-semibold uppercase tracking-wide text-body">{label}</dt><dd className="mt-1 truncate font-semibold text-navy">{value||'—'}</dd></div>}
