'use client';
import {useEffect,useMemo,useState} from 'react';
import {createWorkflowShare} from '../lib/operations';
import {getResidents,supabase} from '../lib/supabase';
import type {Resident} from '../lib/types';
import {PartyFilter,ResidentIdentity,matchesParty} from '../shared/ResidentIdentity';

type Assignment={id:number|string;resident_id:number|string;assignee_name:string;assignment_type:string;status:string;notes?:string|null;assigned_at?:string|null};
export default function AssignmentsContent(){
 const [residents,setResidents]=useState<Resident[]>([]),[items,setItems]=useState<Assignment[]>([]),[query,setQuery]=useState(''),[party,setParty]=useState('all'),[house,setHouse]=useState('all'),[box,setBox]=useState('all'),[linkAssignee,setLinkAssignee]=useState(''),[historyAssignee,setHistoryAssignee]=useState(''),[historySearch,setHistorySearch]=useState(''),[editingId,setEditingId]=useState<string|null>(null),[editingName,setEditingName]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[creating,setCreating]=useState(false),[showResidents,setShowResidents]=useState(false);
 async function load(){try{setError('');const [residentRows,response]=await Promise.all([getResidents(),supabase.from('assignments').select('*').order('assigned_at',{ascending:false}).limit(2000)]);if(response.error)throw response.error;setResidents(residentRows);setItems((response.data||[]) as Assignment[])}catch(e){setError(e instanceof Error?e.message:'Unable to load assignments')}}useEffect(()=>{load()},[]);
 const houses=useMemo(()=>[...new Set(residents.map(r=>(r.house||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[residents]);
 const boxes=useMemo(()=>[...new Set(residents.map(r=>(r.election_box||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[residents]);
 const filteredResidents=useMemo(()=>residents.filter(r=>{const text=[r.name,r.national_id,r.phone,r.house,r.lives_in,r.election_box].join(' ').toLowerCase();return matchesParty(r,party)&&(house==='all'||r.house===house)&&(box==='all'||r.election_box===box)&&text.includes(query.toLowerCase())}),[residents,party,house,box,query]);
 const visibleResidents=filteredResidents.slice(0,showResidents?120:12);
 const residentMap=useMemo(()=>new Map(residents.map(r=>[String(r.id),r])),[residents]);
 const assignees=useMemo(()=>[...new Set(items.map(item=>item.assignee_name).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[items]);
 useEffect(()=>{if(!historyAssignee&&assignees.length)setHistoryAssignee(assignees[0])},[assignees,historyAssignee]);
 const selectedItems=useMemo(()=>items.filter(item=>{if(item.assignee_name!==historyAssignee)return false;const resident=residentMap.get(String(item.resident_id));const text=[resident?.name,resident?.national_id,resident?.phone,resident?.house,resident?.lives_in,item.assignee_name].join(' ').toLowerCase();return text.includes(historySearch.toLowerCase())}),[items,residentMap,historyAssignee,historySearch]);
 async function createShare(openWhatsApp:boolean){const assigneeName=linkAssignee.trim();if(!assigneeName){setError('Enter the assignee name before creating the link.');return}if(!filteredResidents.length){setError('No residents match the current filters.');return}setCreating(true);setError('');setMessage('');try{const ids=filteredResidents.map(r=>Number(r.id));const filterLabel=[party!=='all'?party:null,house!=='all'?house:null,box!=='all'?`Box ${box}`:null,query.trim()?`Search: ${query.trim()}`:null].filter(Boolean).join(' · ')||'All matching residents';const result=await createWorkflowShare({workflow:'assignments',title:`Assignment for ${assigneeName} · ${filterLabel}`,status_filter:assigneeName,resident_ids:ids,can_update:true});const link=`${window.location.origin}/Vote/share/?token=${result.token}`;const text=`Hello ${assigneeName}, please open your private assignment link, select the residents you will handle, review your selection, and submit.\n\n${filterLabel}\n${ids.length} residents\n${link}`;if(openWhatsApp){window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}else{await navigator.clipboard.writeText(link);setMessage(`Private assignment link copied for ${assigneeName} with ${ids.length} residents.`)}}catch(e){setError(e instanceof Error?e.message:'Share failed')}finally{setCreating(false)}}
 function clearFilters(){setQuery('');setParty('all');setHouse('all');setBox('all')}
 function chooseAssignee(name:string){setHistoryAssignee(name);setHistorySearch('');window.setTimeout(()=>document.getElementById('assignee-residents')?.scrollIntoView({behavior:'smooth',block:'start'}),50)}
 function beginEdit(item:Assignment){setEditingId(String(item.id));setEditingName(item.assignee_name)}
 async function saveEdit(item:Assignment){const name=editingName.trim();if(!name){setError('Assignee name cannot be empty.');return}const {error}=await supabase.from('assignments').update({assignee_name:name}).eq('id',item.id);if(error){setError(error.message);return}setEditingId(null);setEditingName('');setHistoryAssignee(name);setMessage('Assignment updated.');load()}
 async function remove(item:Assignment){const resident=residentMap.get(String(item.resident_id));if(!window.confirm(`Delete ${resident?.name||`resident ${item.resident_id}`} from ${item.assignee_name}'s assignments?`))return;const {error}=await supabase.from('assignments').delete().eq('id',item.id);if(error){setError(error.message);return}setMessage('Assignment deleted.');load()}
 return <div className="space-y-4">
  <section className="page-hero"><p className="eyebrow">Field ownership</p><h1 className="mt-2">Assignments</h1><p className="mt-2 text-sm text-body">Create a private link for one named assignee. A resident may be assigned to several different people.</p><div className="mt-4"><PartyFilter value={party} onChange={setParty}/></div></section>
  <section className="panel"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[240px_1fr_220px_200px_auto]"><div><label className="field-label">Assignee name</label><input className="field" value={linkAssignee} onChange={e=>setLinkAssignee(e.target.value)} placeholder="Example: Shaam"/></div><div><label className="field-label">Search residents</label><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, ID, mobile, address or box"/></div><div><label className="field-label">Official address</label><select className="field" value={house} onChange={e=>setHouse(e.target.value)}><option value="all">All houses</option>{houses.map(item=><option key={item} value={item}>{item}</option>)}</select></div><div><label className="field-label">Election box</label><select className="field" value={box} onChange={e=>setBox(e.target.value)}><option value="all">All election boxes</option>{boxes.map(item=><option key={item} value={item}>Box {item}</option>)}</select></div><div className="flex items-end"><button className="btn-secondary w-full" onClick={clearFilters}>Reset filters</button></div></div><div className="mt-4 flex flex-col gap-3 rounded-xl border border-border bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-navy">{filteredResidents.length.toLocaleString()} residents in this private link</b><p className="mt-1 text-xs text-body">The receiver sees only this list and only their own selections.</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={creating} onClick={()=>createShare(false)}>Copy private link</button><button className="btn-primary" disabled={creating} onClick={()=>createShare(true)}>{creating?'Creating…':'Send through WhatsApp'}</button></div></div>{message&&<p className="mt-3 text-sm font-semibold text-accent">{message}</p>}{error&&<div className="error-banner mt-3">{error}</div>}</section>
  <section className="panel sticky top-0 z-10"><div className="grid gap-3 lg:grid-cols-[260px_1fr]"><div><label className="field-label">Show assignee</label><select className="field" value={historyAssignee} onChange={e=>chooseAssignee(e.target.value)}>{assignees.map(name=><option key={name} value={name}>{name}</option>)}</select></div><div><label className="field-label">Search this assignee's residents</label><input className="field" value={historySearch} onChange={e=>setHistorySearch(e.target.value)} placeholder="Resident name, ID, mobile or address"/></div></div></section>
  {historyAssignee&&<section id="assignee-residents" className="panel scroll-mt-28 overflow-hidden p-0"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="eyebrow">Assignee</p><h2 className="mt-1">{historyAssignee}</h2></div><span className="status-chip bg-primary-light text-primary">{selectedItems.length} resident{selectedItems.length===1?'':'s'}</span></div><div className="max-h-[620px] divide-y divide-border overflow-y-auto">{selectedItems.slice(0,100).map(item=>{const resident=residentMap.get(String(item.resident_id)),editing=editingId===String(item.id);return <article key={String(item.id)} className="p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0 flex-1">{resident?<ResidentIdentity resident={resident}/>:<b>Resident {item.resident_id}</b>}<p className="mt-1 text-xs text-body">Resident ID {item.resident_id}{item.assigned_at?` · ${new Date(item.assigned_at).toLocaleString()}`:''}</p></div>{editing?<div className="flex w-full flex-col gap-2 sm:flex-row lg:w-auto"><input className="field min-w-[220px]" value={editingName} onChange={e=>setEditingName(e.target.value)} autoFocus/><button className="btn-primary" onClick={()=>saveEdit(item)}>Save</button><button className="btn-secondary" onClick={()=>{setEditingId(null);setEditingName('')}}>Cancel</button></div>:<div className="flex gap-2"><button className="btn-secondary" onClick={()=>beginEdit(item)}>Modify</button><button className="btn-secondary text-danger" onClick={()=>remove(item)}>Delete</button></div>}</div></article>})}{selectedItems.length>100&&<div className="p-4 text-center text-sm text-body">Showing first 100 residents. Use search to narrow the list.</div>}{!selectedItems.length&&<div className="empty-state m-4">No residents match this assignee and search.</div>}</div></section>}
  {!assignees.length&&<div className="empty-state">No assignment records are available.</div>}
  <section className="panel"><button className="flex w-full items-center justify-between text-left" onClick={()=>setShowResidents(value=>!value)}><div><p className="eyebrow">Link preview</p><h2 className="mt-1">Residents included in this link</h2><p className="mt-1 text-sm text-body">{filteredResidents.length} residents match the current filters.</p></div><span className="btn-secondary">{showResidents?'Hide preview':'Show preview'}</span></button>{showResidents&&<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visibleResidents.map(r=><article key={String(r.id)} className="soft-card"><ResidentIdentity resident={r}/><dl className="mt-4 grid gap-2 text-sm"><Info label="Resident ID" value={String(r.id)}/><Info label="Mobile" value={r.phone}/><Info label="Official address" value={r.house}/><Info label="Living place" value={r.lives_in}/><Info label="Election box" value={r.election_box}/></dl></article>)}</div>}{showResidents&&filteredResidents.length>visibleResidents.length&&<p className="mt-4 text-center text-sm text-body">Showing {visibleResidents.length} of {filteredResidents.length}. Refine the filters for a smaller list.</p>}</section>
 </div>
}
function Info({label,value}:{label:string;value?:string|null}){return <div className="flex justify-between gap-3 border-b border-border pb-2"><dt className="text-body">{label}</dt><dd className="text-right font-semibold text-navy">{value||'—'}</dd></div>}