'use client';
import {FormEvent,useEffect,useState} from 'react';
import type {User} from '@supabase/supabase-js';
import {supabase} from '../lib/supabase';

function EyeIcon({open}:{open:boolean}){
 return open?<svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>:<svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="m3 3 18 18"/><path d="M10.6 10.7a2 2 0 0 0 2.7 2.7"/><path d="M9.9 4.2A10.8 10.8 0 0 1 12 4c6.5 0 10 8 10 8a18 18 0 0 1-2.3 3.5"/><path d="M6.6 6.6C3.7 8.5 2 12 2 12s3.5 8 10 8a9.8 9.8 0 0 0 4.1-.9"/></svg>
}

export default function AuthControl(){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[open,setOpen]=useState(false),[showPassword,setShowPassword]=useState(false),[identity,setIdentity]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;supabase.auth.getUser().then(({data})=>{if(active){setUser(data.user);setIdentity(data.user?.user_metadata?.login_name||data.user?.email||'');setReady(true)}});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);setReady(true);if(session?.user)setOpen(false)});return()=>{active=false;subscription.unsubscribe()}},[]);
 const isAdmin=user?.app_metadata?.role==='admin';
 async function login(event:FormEvent){event.preventDefault();setBusy(true);setError('');const {error:authError}=await supabase.auth.signInWithPassword({email:(identity.trim().includes('@')?identity.trim():`${identity.trim().toLowerCase()}@users.campaignops.invalid`),password});if(authError)setError(authError.message);else setPassword('');setBusy(false)}
 async function signOut(){setBusy(true);setError('');const {error:authError}=await supabase.auth.signOut();if(authError)setError(authError.message);setBusy(false)}
 if(!ready)return <div className="h-10 w-24 animate-pulse rounded-xl bg-primary-light"/>;
 return <>
  {user?<div className="flex items-center gap-2"><div className="hidden min-w-0 text-right sm:block"><p className="max-w-48 truncate text-xs font-semibold text-navy">{user.email}</p><p className="text-[11px] text-body">{isAdmin?'Administrator':'Signed in'}</p></div><button type="button" className="btn-secondary whitespace-nowrap" disabled={busy} onClick={signOut}>{busy?'Signing out…':'Sign out'}</button></div>:<button type="button" className="btn-primary" onClick={()=>{setError('');setOpen(true)}}>Login</button>}
  {open&&!user&&<div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/45 p-0 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="login-title" onMouseDown={event=>{if(event.currentTarget===event.target)setOpen(false)}}><div className="w-full rounded-t-3xl bg-card p-5 shadow-2xl sm:max-w-md sm:rounded-3xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Secure access</p><h2 id="login-title" className="mt-1 text-2xl">Login</h2><p className="mt-1 text-sm text-body">Your session stays saved on this device until you sign out.</p></div><button type="button" className="grid h-10 w-10 place-items-center rounded-full border border-border text-xl text-body" aria-label="Close login" onClick={()=>setOpen(false)}>×</button></div><form className="mt-6 space-y-4" onSubmit={login}><label className="block"><span className="mb-1.5 block text-sm font-semibold text-navy">Email or username</span><input className="field" type="text" value={identity} onChange={event=>setIdentity(event.target.value)} autoComplete="username" required autoFocus placeholder="Username or admin email"/></label><label className="block"><span className="mb-1.5 block text-sm font-semibold text-navy">Password</span><span className="relative block"><input className="field pr-14" type={showPassword?'text':'password'} value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password" required placeholder="Enter password"/><button type="button" className="absolute inset-y-0 right-1 my-auto grid h-10 w-11 place-items-center rounded-lg text-body hover:bg-primary-light hover:text-primary" aria-label={showPassword?'Hide password':'Show password'} aria-pressed={showPassword} onClick={()=>setShowPassword(value=>!value)}><EyeIcon open={showPassword}/></button></span></label><div className="rounded-xl border border-border bg-slate-50 px-3 py-2 text-xs text-body">The website saves the login session. Your browser may securely offer to save the password.</div>{error&&<div className="error-banner">{error}</div>}<button className="btn-primary w-full" type="submit" disabled={busy}>{busy?'Logging in…':'Login securely'}</button></form></div></div>}
 </>
}
