'use client';
import {useEffect,useState} from 'react';
import {getCallCenterQueue,saveCallCenterResult} from '../lib/supabase';
import type {CallOutcome,Resident,SupportLevel,VoteStatus} from '../lib/types';
import {PartyFilter,ResidentIdentity} from '../shared/ResidentIdentity';

const outcomes:CallOutcome[]=['connected','busy','not-answer','out-of-coverage','disconnected','wrong-number'];
const text=(value:string)=>value.replace(/-/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
export default function CallCenterContent(){
 const [rows,setRows]=useState<Resident[]>([]),[count,setCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');const [search,setSearch]=useState(''),[party,setParty]=useState('all'),[status,setStatus]=useState('need-call'),[selected,setSelected]=useState<Resident|null>(null);
 function load(){setLoading(true);getCallCenterQueue({search,party,phoneStatus:status,pageSize:100}).then(r=>{setRows(r.rows);setCount(r.count);setError('')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
 useEffect(()=>{const timer=window.setTimeout(load,250);return()=>window.clearTimeout(timer)},[search,party,status]);
 return <div className="space-y-4"><section className="page-hero"><p className="eyebrow">Call Center</p><h1 className="mt-2">Phone outreach</h1><p className="mt-2 text-sm text-body">{count.toLocaleString()} residents in the selected queue.</p><div className="mt-4"><PartyFilter value={party} onChange={setParty}/></div></section><section className="panel"><div className="grid gap-3 md:grid-cols-[1fr_220px]"><input className="field" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, ID, phone or address"/><select className="field" value={status} onChange={e=>setStatus(e.target.value)}><option value="need-call">Need call</option><option value="called">Called</option><option value="all">All records</option></select></div></section>{error&&<div className="error-banner">{error}</div>}<section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{loading?Array.from({length:6}).map((_,i)=><div key={i} className="h-52 animate-pulse bg-primary-light"/>):rows.map(r=><article key={String(r.id)} className="soft-card"><ResidentIdentity resident={r}/><p className="mt-4 font-semibold text-navy">{r.phone||'No phone'}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><Box label="Attempts" value={String(r.call_attempts||0)}/><Box label="Last result" value={text(r.call_outcome||'not called')}/></div><button onClick={()=>setSelected(r)} className="btn-primary mt-4 w-full">Record call</button></article>)}</section>{selected&&<CallForm resident={selected} close={()=>setSelected(null)} saved={()=>{setSelected(null);load()}}/>}</div>
}
function CallForm({resident,close,saved}:{resident:Resident;close:()=>void;saved:()=>void}){const [outcome,setOutcome]=useState<CallOutcome>('connected'),[vote,setVote]=useState<VoteStatus>('not-decided'),[support,setSupport]=useState<SupportLevel>('not-guaranteed'),[notes,setNotes]=useState(''),[agent,setAgent]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');const connected=outcome==='connected';async function submit(){setSaving(true);try{await saveCallCenterResult(resident.id,{outcome,vote_status:vote,support_level:support,notes,recorded_by:agent});saved()}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}return <div className="fixed inset-0 z-50 flex justify-end bg-navy/40"><aside className="h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl"><header className="sticky top-0 border-b border-border bg-white p-5"><div className="flex justify-between gap-3"><ResidentIdentity resident={resident}/><button className="btn-ghost" onClick={close}>Close</button></div></header><div className="space-y-5 p-5"><ChoiceGroup title="Call result" values={outcomes} selected={outcome} choose={v=>setOutcome(v as CallOutcome)}/><div className={!connected?'pointer-events-none opacity-40':''}><ChoiceGroup title="Vote answer" values={['will-vote','not-decided','not-vote']} selected={vote} choose={v=>setVote(v as VoteStatus)}/><ChoiceGroup title="Support" values={['guaranteed','not-guaranteed']} selected={support} choose={v=>setSupport(v as SupportLevel)}/></div><textarea className="field min-h-28" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Call notes"/><input className="field" value={agent} onChange={e=>setAgent(e.target.value)} placeholder="Agent name"/>{error&&<div className="error-banner">{error}</div>}<button disabled={saving} onClick={submit} className="btn-primary w-full">{saving?'Saving…':'Save result'}</button></div></aside></div>}
function ChoiceGroup({title,values,selected,choose}:{title:string;values:string[];selected:string;choose:(v:string)=>void}){return <section><h3>{title}</h3><div className="mt-3 grid grid-cols-2 gap-2">{values.map(v=><button key={v} onClick={()=>choose(v)} className={`rounded-lg border p-3 text-sm font-semibold ${selected===v?'border-primary bg-primary-light text-primary':'border-border text-body'}`}>{text(v)}</button>)}</div></section>}function Box({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><span className="block text-body">{label}</span><b className="block truncate text-navy">{value}</b></div>}
