'use client';
import {useEffect,useState} from 'react';
import {getCallCenterQueue,saveCallCenterResult} from '../lib/supabase';
import type {CallOutcome,Resident,SupportLevel,VoteStatus} from '../lib/types';
import {PartyBadge,PartyLegend,partyBorder} from '../shared/PartyIdentity';

const outcomes:CallOutcome[]=['connected','busy','not-answer','out-of-coverage','disconnected','wrong-number'];
const text=(value:string)=>value.replace(/-/g,' ').replace(/\b\w/g,m=>m.toUpperCase());

export default function CallCenterContent(){
 const [rows,setRows]=useState<Resident[]>([]),[count,setCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [search,setSearch]=useState(''),[party,setParty]=useState('all'),[status,setStatus]=useState('need-call'),[selected,setSelected]=useState<Resident|null>(null);
 function load(){setLoading(true);getCallCenterQueue({search,party,phoneStatus:status,pageSize:100}).then(r=>{setRows(r.rows);setCount(r.count);setError('')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
 useEffect(()=>{const timer=window.setTimeout(load,250);return()=>window.clearTimeout(timer)},[search,party,status]);
 return <div className="space-y-5">
  <section className="rounded-3xl border border-violet-200 bg-white shadow-card"><div className="border-l-8 border-violet-600 p-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="flex items-center gap-3"><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-extrabold text-violet-700">CALL CENTER</span><PartyLegend/></div><h1 className="mt-3 text-3xl font-black text-navy">Phone outreach</h1><p className="mt-2 text-sm text-body">Resident data is read-only. Results save only to call_center.</p></div><div className="rounded-2xl bg-violet-50 px-5 py-3"><b className="text-2xl text-violet-800">{count.toLocaleString()}</b><span className="ml-2 text-xs font-bold text-violet-600">in queue</span></div></div></div></section>
  <section className="panel space-y-4"><div className="grid gap-3 lg:grid-cols-[1fr_auto_210px]"><input className="field" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, ID, phone or address"/><div className="flex rounded-full border border-border bg-slate-50 p-1">{['all','PNC','MDP','Other'].map(p=><button key={p} onClick={()=>setParty(p)} className={`rounded-full px-3 py-2 text-xs font-extrabold ${party===p?(p==='PNC'?'bg-teal-600 text-white':p==='MDP'?'bg-yellow-400 text-slate-900':'bg-violet-600 text-white'):'text-body'}`}>{p==='all'?'All':p}</button>)}</div><select className="field" value={status} onChange={e=>setStatus(e.target.value)}><option value="need-call">Need call</option><option value="called">Called</option><option value="all">All records</option></select></div><div className="rounded-2xl bg-violet-50 p-4 text-sm text-violet-900"><b>Logic:</b> every saved attempt is Called. Only Connected is Reached. Vote and support are recorded only on connected calls.</div></section>
  {error&&<div className="error-banner">{error}</div>}
  <section className="panel p-0"><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{loading?Array.from({length:6}).map((_,i)=><div key={i} className="h-52 animate-pulse rounded-2xl bg-violet-50"/>):rows.map(r=><article key={String(r.id)} className={`rounded-2xl border border-border bg-white p-5 shadow-sm ${partyBorder(r.party)}`}><div className="flex justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-extrabold text-navy">{r.name||'Unnamed resident'}</h2><p className="text-xs text-body">{r.national_id||'No ID'}</p></div><PartyBadge party={r.party}/></div><p className="mt-4 font-bold text-navy">{r.phone||'No phone'}</p><p className="mt-1 truncate text-xs text-body">{r.house||'No address'} · {r.lives_in||'Living place unknown'}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><Box label="Attempts" value={String(r.call_attempts||0)}/><Box label="Last result" value={text(r.call_outcome||'not called')}/></div><button onClick={()=>setSelected(r)} className="mt-4 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-extrabold text-white">Record call</button></article>)}</div>{!loading&&!rows.length&&<p className="p-12 text-center text-body">No residents match this queue.</p>}</section>
  {selected&&<CallForm resident={selected} close={()=>setSelected(null)} saved={()=>{setSelected(null);load()}}/>}
 </div>
}

function CallForm({resident,close,saved}:{resident:Resident;close:()=>void;saved:()=>void}){
 const [outcome,setOutcome]=useState<CallOutcome>('connected'),[vote,setVote]=useState<VoteStatus>('not-decided'),[support,setSupport]=useState<SupportLevel>('not-guaranteed'),[notes,setNotes]=useState(''),[agent,setAgent]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const connected=outcome==='connected';async function submit(){setSaving(true);try{await saveCallCenterResult(resident.id,{outcome,vote_status:vote,support_level:support,notes,recorded_by:agent});saved()}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-50 flex justify-end bg-navy/40"><aside className="h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl"><header className={`sticky top-0 border-b border-border bg-white p-5 ${partyBorder(resident.party)}`}><div className="flex justify-between gap-3"><div><PartyBadge party={resident.party}/><h2 className="mt-2 text-2xl font-black text-navy">{resident.name}</h2><p className="text-sm text-body">{resident.phone||'No phone'} · {resident.house||'No address'}</p></div><button className="btn-ghost" onClick={close}>Close</button></div></header><div className="space-y-5 p-5"><ChoiceGroup title="Call result" values={outcomes} selected={outcome} choose={v=>setOutcome(v as CallOutcome)}/><div className={!connected?'pointer-events-none opacity-40':''}><ChoiceGroup title="Vote answer" values={['will-vote','not-decided','not-vote']} selected={vote} choose={v=>setVote(v as VoteStatus)}/><ChoiceGroup title="Support" values={['guaranteed','not-guaranteed']} selected={support} choose={v=>setSupport(v as SupportLevel)}/></div><textarea className="field min-h-28" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Call notes"/><input className="field" value={agent} onChange={e=>setAgent(e.target.value)} placeholder="Agent name"/>{error&&<div className="error-banner">{error}</div>}<button disabled={saving} onClick={submit} className="w-full rounded-xl bg-violet-600 px-5 py-4 font-extrabold text-white disabled:opacity-50">{saving?'Saving…':'Save Call Center result'}</button></div></aside></div>
}
function ChoiceGroup({title,values,selected,choose}:{title:string;values:string[];selected:string;choose:(v:string)=>void}){return <section><h3 className="font-extrabold text-navy">{title}</h3><div className="mt-3 grid grid-cols-2 gap-2">{values.map(v=><button key={v} onClick={()=>choose(v)} className={`rounded-xl border p-3 text-sm font-bold ${selected===v?'border-violet-600 bg-violet-50 text-violet-800':'border-border text-body'}`}>{text(v)}</button>)}</div></section>}
function Box({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><span className="block text-body">{label}</span><b className="block truncate text-navy">{value}</b></div>}
