'use client';
import {useEffect,useMemo,useState} from 'react';
import {createWorkflowShare,getElectionBoard,saveElectionStatus} from '../lib/operations';
import type {Resident} from '../lib/types';

type Row={resident:Resident;election:{resident_id:number|string;reach_status:'reached'|'not-reached';has_voted:boolean;transport_status:string;contact_note?:string|null}};
type Filter='all'|'reached'|'not-reached'|'voted'|'not-voted';

export default function ElectionDayContent(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState<Filter>('all'),[query,setQuery]=useState(''),[saving,setSaving]=useState<string>(''),[shareMessage,setShareMessage]=useState('');
 async function load(){setLoading(true);setError('');try{setRows(await getElectionBoard() as Row[])}catch(e){setError(e instanceof Error?e.message:'Unable to load Election Day')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const totals=useMemo(()=>({all:rows.length,reached:rows.filter(r=>r.election.reach_status==='reached').length,notReached:rows.filter(r=>r.election.reach_status!=='reached').length,voted:rows.filter(r=>r.election.has_voted).length,notVoted:rows.filter(r=>!r.election.has_voted).length}),[rows]);
 const visible=useMemo(()=>rows.filter(row=>{const matches=filter==='all'||filter==='reached'&&row.election.reach_status==='reached'||filter==='not-reached'&&row.election.reach_status!=='reached'||filter==='voted'&&row.election.has_voted||filter==='not-voted'&&!row.election.has_voted;const text=[row.resident.name,row.resident.national_id,row.resident.phone,row.resident.lives_in,row.resident.election_box].join(' ').toLowerCase();return matches&&text.includes(query.toLowerCase())}).slice(0,120),[rows,filter,query]);
 async function update(row:Row,changes:any){const key=String(row.resident.id);setSaving(key);setError('');try{await saveElectionStatus(row.resident.id,changes);setRows(current=>current.map(item=>String(item.resident.id)===key?{...item,election:{...item.election,...changes}}:item))}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving('')}}
 async function share(kind:Exclude<Filter,'all'>){setShareMessage('');try{const item=await createWorkflowShare({workflow:'election-day',title:`Election Day · ${label(kind)}`,status_filter:kind});const url=`${window.location.origin}/Vote/share/?token=${item.token}`;await navigator.clipboard.writeText(url);setShareMessage(`${label(kind)} share link copied.`)}catch(e){setError(e instanceof Error?e.message:'Could not create share link')}}
 return <div className="space-y-4">
  <section className="page-hero"><p className="eyebrow">Election operations</p><h1 className="mt-2">Election Day Control Board</h1><p className="mt-2 max-w-3xl text-sm text-body">Track who has been reached, who has voted, and who still requires action. Resident identity remains read-only.</p></section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="All residents" value={totals.all} active={filter==='all'} onClick={()=>setFilter('all')}/><Metric label="Reached" value={totals.reached} active={filter==='reached'} onClick={()=>setFilter('reached')}/><Metric label="Not reached" value={totals.notReached} active={filter==='not-reached'} onClick={()=>setFilter('not-reached')}/><Metric label="Voted" value={totals.voted} active={filter==='voted'} onClick={()=>setFilter('voted')}/><Metric label="Not voted" value={totals.notVoted} active={filter==='not-voted'} onClick={()=>setFilter('not-voted')}/></section>
  <section className="panel"><div className="grid gap-3 lg:grid-cols-[1fr_auto]"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, ID, mobile, living place or election box"/><div className="flex flex-wrap gap-2"><Share label="Reached" onClick={()=>share('reached')}/><Share label="Not reached" onClick={()=>share('not-reached')}/><Share label="Voted" onClick={()=>share('voted')}/><Share label="Not voted" onClick={()=>share('not-voted')}/></div></div>{shareMessage&&<p className="mt-3 text-sm font-semibold text-accent">{shareMessage}</p>}{error&&<div className="error-banner mt-3">{error}</div>}</section>
  <section className="panel overflow-hidden p-0"><div className="border-b border-border px-5 py-4"><b className="text-navy">{visible.length.toLocaleString()} visible records</b><p className="text-sm text-body">Showing the first 120 matching residents for fast Election Day operation.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-primary-light"><tr><Th>Resident</Th><Th>National ID</Th><Th>Mobile</Th><Th>Living place</Th><Th>Box</Th><Th>Reach</Th><Th>Turnout</Th><Th>Transport</Th></tr></thead><tbody>{loading?Array.from({length:8}).map((_,i)=><tr key={i}><td colSpan={8} className="p-4"><div className="h-12 animate-pulse bg-primary-light"/></td></tr>):visible.map(row=><tr key={String(row.resident.id)} className="border-b border-border"><td className="p-4 font-bold text-navy">{row.resident.name||'Unnamed'}</td><td className="p-4">{row.resident.national_id||'—'}</td><td className="p-4">{row.resident.phone||'—'}</td><td className="p-4">{row.resident.lives_in||'—'}</td><td className="p-4">{row.resident.election_box||'—'}</td><td className="p-4"><button disabled={saving===String(row.resident.id)} className={row.election.reach_status==='reached'?'btn-primary':'btn-secondary'} onClick={()=>update(row,{reach_status:row.election.reach_status==='reached'?'not-reached':'reached'})}>{row.election.reach_status==='reached'?'Reached':'Not reached'}</button></td><td className="p-4"><button disabled={saving===String(row.resident.id)} className={row.election.has_voted?'btn-primary':'btn-secondary'} onClick={()=>update(row,{has_voted:!row.election.has_voted})}>{row.election.has_voted?'Voted':'Not voted'}</button></td><td className="p-4"><span className="status-chip bg-primary-light text-body">{row.election.transport_status.replaceAll('-',' ')}</span></td></tr>)}</tbody></table></div></section>
 </div>
}
function label(value:string){return value.replaceAll('-',' ').replace(/^./,x=>x.toUpperCase())}
function Metric({label,value,active,onClick}:{label:string;value:number;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`metric-card text-left ${active?'ring-2 ring-primary':''}`}><span className="eyebrow">{label}</span><strong className="mt-2 block text-3xl text-navy">{value.toLocaleString()}</strong></button>}
function Share({label,onClick}:{label:string;onClick:()=>void}){return <button className="btn-secondary whitespace-nowrap" onClick={onClick}>Share {label}</button>}
function Th({children}:{children:React.ReactNode}){return <th className="p-4 text-[11px] uppercase tracking-[.12em] text-body">{children}</th>}
