'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {getResidents,getResidentsPage} from '../lib/supabase';
import type {Resident} from '../lib/types';
import StatusBadge from '../shared/StatusBadge';
import {PartyFilter,ResidentIdentity,matchesParty} from '../shared/ResidentIdentity';

type Mode='calls'|'visits'|'election'|'reports'|'notifications'|'settings';
export default function OperationsListContent({mode}:{mode:Mode}){
 const [rows,setRows]=useState<Resident[]>([]),[count,setCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[party,setParty]=useState('all');
 useEffect(()=>{let active=true;setLoading(true);setError('');const request=mode==='visits'?getResidentsPage({page:1,pageSize:60,party}):getResidents().then(data=>({rows:data,count:data.length}));request.then(result=>{if(active){setRows(result.rows);setCount(result.count)}}).catch(e=>active&&setError(e.message||'Unable to load campaign data')).finally(()=>active&&setLoading(false));return()=>{active=false}},[mode,party]);
 const config={calls:{title:'Call Center',description:'Phone outreach queue.',filter:(r:Resident)=>!r.phone_status||r.phone_status==='need-call'},visits:{title:'Door-to-Door',description:'Field visit queue. Showing the first 60 matching residents for fast loading.',filter:(r:Resident)=>!r.d2d_status||r.d2d_status==='not-visited'},election:{title:'Election Day',description:'Turnout and readiness.',filter:(_:Resident)=>true},reports:{title:'Reports',description:'Cross-section totals.',filter:(_:Resident)=>true},notifications:{title:'Notifications',description:'Items needing attention.',filter:(r:Resident)=>r.vote_status==='not-decided'||r.phone_status==='need-call'},settings:{title:'Settings',description:'System configuration.',filter:(_:Resident)=>true}}[mode];
 const visible=useMemo(()=>rows.filter(r=>(mode==='visits'||matchesParty(r,party))&&config.filter(r)),[rows,party,config,mode]);
 if(mode==='settings')return <div className="panel"><h1>Settings</h1><p className="mt-2 text-sm text-body">Connected to public.Resident · {rows.length.toLocaleString()} residents.</p></div>;
 if(mode==='reports'){const will=visible.filter(r=>r.vote_status==='will-vote').length,called=visible.filter(r=>r.phone_status==='called').length,visited=visible.filter(r=>r.d2d_status&&r.d2d_status!=='not-visited').length;return <div className="space-y-4"><section className="page-hero"><p className="eyebrow">Analytics</p><h1 className="mt-2">Reports</h1><div className="mt-4"><PartyFilter value={party} onChange={setParty}/></div></section><div className="grid gap-4 md:grid-cols-3"><Card label="Will vote" value={will}/><Card label="Calls completed" value={called}/><Card label="Homes visited" value={visited}/></div></div>}
 return <div className="space-y-4"><section className="page-hero"><p className="eyebrow">Campaign operations</p><h1 className="mt-2">{config.title}</h1><p className="mt-2 text-sm text-body">{config.description}</p><div className="mt-4"><PartyFilter value={party} onChange={setParty}/></div></section>{error&&<div className="error-banner">{error}</div>}<section className="panel overflow-hidden p-0"><div className="border-b border-border px-5 py-4"><b className="text-navy">{count.toLocaleString()} matching residents</b></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{loading?Array.from({length:6}).map((_,i)=><div key={i} className="h-48 animate-pulse rounded-xl bg-primary-light"/>):visible.map(r=><WorkCard key={String(r.id)} resident={r} mode={mode}/>)}</div></section></div>
}
function WorkCard({resident:r,mode}:{resident:Resident;mode:Mode}){return <article className="soft-card"><ResidentIdentity resident={r}/><div className="mt-4 grid gap-2 text-sm"><Info label="Official house" value={r.house}/><Info label="Mobile" value={r.phone}/></div><div className="mt-4 flex flex-wrap gap-2"><StatusBadge status={mode==='calls'?r.phone_status:r.d2d_status}/><StatusBadge status={r.vote_status}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><Link prefetch href={`/resident-profile/?id=${encodeURIComponent(String(r.id))}`} className="btn-primary w-full">Open resident</Link><Link prefetch href={`/remarks/?resident=${encodeURIComponent(String(r.id))}&section=${mode==='visits'?'door-to-door':'general'}`} className="btn-secondary w-full">Add remark</Link></div></article>}
function Info({label,value}:{label:string,value?:string|null}){return <div className="flex justify-between gap-3"><span className="text-body">{label}</span><strong className="text-right text-navy">{value||'Not recorded'}</strong></div>}
function Card({label,value}:{label:string,value:number}){return <div className="metric-card"><p className="eyebrow">{label}</p><strong className="mt-2 block text-4xl text-navy">{value.toLocaleString()}</strong></div>}