'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {getResidents} from '../lib/supabase';
import type {Resident} from '../lib/types';
import StatusBadge from '../shared/StatusBadge';

type Mode='calls'|'visits'|'election'|'reports'|'notifications'|'settings';
export default function OperationsListContent({mode}:{mode:Mode}){
 const [rows,setRows]=useState<Resident[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{getResidents().then(setRows).catch(e=>setError(e.message||'Unable to load campaign data')).finally(()=>setLoading(false))},[]);
 const config={calls:{title:'Call Center',description:'Phone outreach queue with contact, living address and remarks.',filter:(r:Resident)=>!r.phone_status||r.phone_status==='need-call'},visits:{title:'Door-to-Door',description:'Mobile field queue with official house, living location and important remarks.',filter:(r:Resident)=>!r.d2d_status||r.d2d_status==='not-visited'},election:{title:'Election Day',description:'Live readiness, commitment and transport overview.',filter:(r:Resident)=>r.vote_status==='will-vote'||r.support_level==='guaranteed'},reports:{title:'Reports',description:'Campaign completion totals calculated from live records.',filter:(_:Resident)=>true},notifications:{title:'Notifications',description:'Operational items requiring attention.',filter:(r:Resident)=>r.vote_status==='not-decided'||r.phone_status==='need-call'},settings:{title:'Settings',description:'Campaign configuration and connection status.',filter:(_:Resident)=>true}}[mode];
 const visible=useMemo(()=>rows.filter(config.filter),[rows,config]);
 if(mode==='settings')return <div className="space-y-6"><section><p className="muted">Administration</p><h1 className="text-3xl font-bold">Settings</h1></section><section className="panel space-y-4"><div className="soft-card"><b>Supabase connection</b><p className="mt-1 text-sm text-slate-500">Connected to public.campaign · {rows.length.toLocaleString()} residents available.</p></div><div className="soft-card"><b>Deployment</b><p className="mt-1 text-sm text-slate-500">Next.js static export hosted at /Vote through GitHub Pages.</p></div></section></div>;
 if(mode==='reports'){const will=rows.filter(r=>r.vote_status==='will-vote').length,called=rows.filter(r=>r.phone_status==='called').length,visited=rows.filter(r=>r.d2d_status&&r.d2d_status!=='not-visited').length;return <div className="space-y-6"><section><p className="muted">Analytics</p><h1 className="text-3xl font-bold">Reports</h1></section><div className="grid gap-4 md:grid-cols-3"><Card label="Will vote" value={will}/><Card label="Calls completed" value={called}/><Card label="Homes visited" value={visited}/></div></div>}
 return <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-br from-[#17324D] to-[#0F5960] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-100">Campaign operations</p><h1 className="mt-2 text-3xl font-extrabold">{config.title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-200">{config.description}</p></section>{error&&<div className="panel text-rose-700">{error}</div>}<section className="panel p-0 overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><b>{visible.length.toLocaleString()} matching residents</b><p className="mt-1 text-sm text-slate-500">Open a resident to update mobile, living address, status and remarks.</p></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{loading?Array.from({length:6}).map((_,i)=><div key={i} className="h-56 animate-pulse rounded-2xl bg-slate-100"/>):visible.slice(0,120).map(r=><WorkCard key={String(r.id)} resident={r} mode={mode}/>)}</div>{!loading&&visible.length>120&&<p className="border-t border-slate-200 p-4 text-sm text-slate-500">Showing first 120 records. Use Residents for full filtering.</p>}</section></div>;
}
function WorkCard({resident:r,mode}:{resident:Resident;mode:Mode}){return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-base font-extrabold text-slate-900">{r.name||'Unnamed resident'}</h2><p className="mt-1 text-xs font-semibold text-slate-500">{r.national_id||'No national ID'}</p></div><StatusBadge status={mode==='calls'?r.phone_status:r.d2d_status}/></div><div className="mt-4 grid gap-2 text-sm"><Info label="Official house" value={r.house}/><Info label="Living now" value={r.lives_in}/><Info label="Mobile" value={r.phone}/></div><div className={`mt-4 rounded-xl border p-3 ${r.remarks?'border-amber-200 bg-amber-50':'border-slate-200 bg-slate-50'}`}><p className="text-[11px] font-extrabold uppercase tracking-wide text-slate-500">Important remarks</p><p className="mt-1 line-clamp-3 text-sm font-medium text-slate-700">{r.remarks||'No remarks recorded'}</p></div><div className="mt-4 flex flex-wrap gap-2"><StatusBadge status={r.vote_status}/><StatusBadge status={r.support_level}/></div><Link prefetch={false} href={`/voter-detail/?id=${encodeURIComponent(String(r.id))}`} className="action mt-4 w-full bg-[#0F8B8D] text-white hover:bg-[#0C7476]">Open and update</Link></article>}
function Info({label,value}:{label:string,value?:string|null}){return <div className="flex items-start justify-between gap-3"><span className="text-slate-400">{label}</span><strong className="max-w-[65%] text-right text-slate-700">{value||'Not recorded'}</strong></div>}
function Card({label,value}:{label:string,value:number}){return <div className="panel"><p className="muted">{label}</p><strong className="mt-2 block text-4xl font-bold">{value.toLocaleString()}</strong></div>}