'use client';
import {useEffect,useMemo,useState} from 'react';
import {getResidents,supabase} from '../lib/supabase';
import type {Resident} from '../lib/types';

type Remark={id:number|string;resident_id:number|string;section:string;remark:string;recorded_by?:string|null;recorded_at?:string|null};
export default function RemarksContent(){
 const [residents,setResidents]=useState<Resident[]>([]),[items,setItems]=useState<Remark[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[section,setSection]=useState('general'),[remark,setRemark]=useState(''),[recordedBy,setRecordedBy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){try{const [residentRows,response]=await Promise.all([getResidents(),supabase.from('remarks').select('*').order('recorded_at',{ascending:false}).limit(300)]);if(response.error)throw response.error;setResidents(residentRows);setItems((response.data||[]) as Remark[])}catch(e){setError(e instanceof Error?e.message:'Unable to load remarks')}}
 useEffect(()=>{load()},[]);
 const matches=useMemo(()=>residents.filter(r=>[r.name,r.national_id,r.phone,r.lives_in].join(' ').toLowerCase().includes(query.toLowerCase())).slice(0,20),[residents,query]);
 const map=useMemo(()=>new Map(residents.map(r=>[String(r.id),r])),[residents]);
 async function save(){if(!selected||!remark.trim()){setError('Select a resident and enter a remark.');return}setError('');const {error}=await supabase.from('remarks').insert({id:Date.now(),resident_id:Number(selected),section,remark:remark.trim(),recorded_by:recordedBy.trim()||null,recorded_at:new Date().toISOString()});if(error){setError(error.message);return}setMessage('Remark saved.');setRemark('');load()}
 return <div className="space-y-4"><section className="page-hero"><p className="eyebrow">Operational history</p><h1 className="mt-2">Remarks</h1><p className="mt-2 text-sm text-body">Store section-specific notes without changing the resident identity table.</p></section><section className="panel"><div className="grid gap-3 lg:grid-cols-2"><div className="relative"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search resident"/>{query&&<div className="absolute z-20 mt-1 max-h-72 w-full overflow-y-auto border border-border bg-card shadow-card">{matches.map(r=><button key={String(r.id)} className="block w-full border-b border-border p-3 text-left hover:bg-primary-light" onClick={()=>{setSelected(String(r.id));setQuery(r.name||String(r.id))}}><b className="text-navy">{r.name}</b><span className="ml-2 text-xs text-body">{r.national_id}</span></button>)}</div>}</div><select className="field" value={section} onChange={e=>setSection(e.target.value)}><option value="general">General</option><option value="call-center">Call Center</option><option value="door-to-door">Door-to-Door</option><option value="election-day">Election Day</option><option value="transportation">Transportation</option></select><input className="field" value={recordedBy} onChange={e=>setRecordedBy(e.target.value)} placeholder="Recorded by"/><textarea className="field min-h-28 py-3" value={remark} onChange={e=>setRemark(e.target.value)} placeholder="Enter a clear operational remark"/></div><div className="mt-3 flex justify-end"><button className="btn-primary" onClick={save}>Save remark</button></div>{message&&<p className="mt-3 text-sm font-semibold text-accent">{message}</p>}{error&&<div className="error-banner mt-3">{error}</div>}</section><section className="panel overflow-hidden p-0"><div className="border-b border-border px-5 py-4"><b className="text-navy">Latest remarks</b></div><div className="divide-y divide-border">{items.map(item=>{const resident=map.get(String(item.resident_id));return <article key={String(item.id)} className="p-4"><div className="flex flex-wrap items-center gap-2"><b className="text-navy">{resident?.name||`Resident ${item.resident_id}`}</b><span className="status-chip bg-primary-light text-body">{item.section}</span></div><p className="mt-2 text-sm text-body">{item.remark}</p><p className="mt-2 text-xs text-body">{item.recorded_by||'Unknown recorder'} · {item.recorded_at?new Date(item.recorded_at).toLocaleString():'—'}</p></article>})}</div></section></div>
}
