'use client';
import {useEffect,useMemo,useState} from 'react';
import {getResidents,supabase} from '../lib/supabase';
import type {Resident} from '../lib/types';
import {PartyFilter,ResidentIdentity,matchesParty} from '../shared/ResidentIdentity';

type Remark={id:number|string;resident_id:number|string;section:string;remark:string;recorded_by?:string|null;recorded_at?:string|null};
export default function RemarksContent(){
 const [residents,setResidents]=useState<Resident[]>([]),[items,setItems]=useState<Remark[]>([]),[query,setQuery]=useState(''),[party,setParty]=useState('all'),[selected,setSelected]=useState(''),[section,setSection]=useState('general'),[remark,setRemark]=useState(''),[recordedBy,setRecordedBy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [editingId,setEditingId]=useState<string|null>(null),[editingRemark,setEditingRemark]=useState(''),[editingSection,setEditingSection]=useState('general'),[savingEdit,setSavingEdit]=useState(false);
 async function load(){try{const [residentRows,response]=await Promise.all([getResidents(),supabase.from('remarks').select('*').order('recorded_at',{ascending:false}).limit(300)]);if(response.error)throw response.error;setResidents(residentRows);setItems((response.data||[]) as Remark[])}catch(e){setError(e instanceof Error?e.message:'Unable to load remarks')}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!residents.length)return;const params=new URLSearchParams(window.location.search),residentId=params.get('resident'),requestedSection=params.get('section');if(requestedSection&&['general','call-center','door-to-door','election-day','transportation'].includes(requestedSection))setSection(requestedSection);if(residentId){const resident=residents.find(r=>String(r.id)===residentId);if(resident){setSelected(residentId);setQuery(resident.name||`Resident ${residentId}`)}}},[residents]);
 const map=useMemo(()=>new Map(residents.map(r=>[String(r.id),r])),[residents]);
 const matches=useMemo(()=>residents.filter(r=>matchesParty(r,party)&&[r.name,r.national_id,r.phone,r.lives_in].join(' ').toLowerCase().includes(query.toLowerCase())).slice(0,20),[residents,query,party]);
 const visibleItems=useMemo(()=>items.filter(item=>{const resident=map.get(String(item.resident_id));return resident?matchesParty(resident,party):party==='all'}),[items,map,party]);
 async function save(){if(!selected||!remark.trim()){setError('Select a resident and enter a remark.');return}const {error}=await supabase.from('remarks').insert({id:Date.now(),resident_id:Number(selected),section,remark:remark.trim(),recorded_by:recordedBy.trim()||null,recorded_at:new Date().toISOString()});if(error){setError(error.message);return}setError('');setMessage('Remark saved.');setRemark('');load()}
 function beginEdit(item:Remark){setEditingId(String(item.id));setEditingRemark(item.remark);setEditingSection(item.section||'general');setError('');setMessage('')}
 function cancelEdit(){setEditingId(null);setEditingRemark('');setEditingSection('general')}
 async function updateRemark(item:Remark){if(!editingRemark.trim()){setError('Remark cannot be empty.');return}setSavingEdit(true);setError('');const {error}=await supabase.from('remarks').update({remark:editingRemark.trim(),section:editingSection}).eq('id',item.id);setSavingEdit(false);if(error){setError(error.message);return}cancelEdit();setMessage('Remark updated.');load()}
 async function deleteRemark(item:Remark){if(!window.confirm('Delete this remark permanently?'))return;setError('');const {error}=await supabase.from('remarks').delete().eq('id',item.id);if(error){setError(error.message);return}if(editingId===String(item.id))cancelEdit();setMessage('Remark deleted.');load()}
 return <div className="space-y-4">
  <section className="page-hero"><p className="eyebrow">Operational history</p><h1 className="mt-2">Remarks</h1><p className="mt-2 text-sm text-body">All workflow comments are stored here by resident and section.</p><div className="mt-4"><PartyFilter value={party} onChange={setParty}/></div></section>
  <section className="panel"><div className="grid gap-3 lg:grid-cols-2"><div className="relative"><input className="field" value={query} onChange={e=>{setQuery(e.target.value);setSelected('')}} placeholder="Search resident"/>{query&&!selected&&<div className="absolute z-20 mt-1 max-h-72 w-full overflow-y-auto rounded-xl border border-border bg-card shadow-card">{matches.map(r=><button key={String(r.id)} className="block w-full border-b border-border p-3 text-left hover:bg-primary-light" onClick={()=>{setSelected(String(r.id));setQuery(r.name||String(r.id))}}><ResidentIdentity resident={r} compact/></button>)}</div>}</div><select className="field" value={section} onChange={e=>setSection(e.target.value)}><option value="general">General</option><option value="call-center">Call Center</option><option value="door-to-door">Door-to-Door</option><option value="election-day">Election Day</option><option value="transportation">Transportation</option></select><input className="field" value={recordedBy} onChange={e=>setRecordedBy(e.target.value)} placeholder="Recorded by"/><textarea className="field min-h-28 py-3" value={remark} onChange={e=>setRemark(e.target.value)} placeholder="Enter a clear operational remark"/></div><div className="mt-3 flex justify-end"><button className="btn-primary" onClick={save}>Save remark</button></div>{message&&<p className="mt-3 text-sm font-semibold text-primary">{message}</p>}{error&&<div className="error-banner mt-3">{error}</div>}</section>
  <section className="panel overflow-hidden p-0"><div className="divide-y divide-border">{visibleItems.map(item=>{const resident=map.get(String(item.resident_id)),editing=editingId===String(item.id);return <article key={String(item.id)} className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div>{resident?<ResidentIdentity resident={resident}/>:<b>Resident {item.resident_id}</b>}</div>{!editing&&<div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>beginEdit(item)}>Edit</button><button className="btn-secondary text-danger" onClick={()=>deleteRemark(item)}>Delete</button></div>}</div>{editing?<div className="mt-4 rounded-xl border border-primary/30 bg-primary-soft p-4"><select className="field" value={editingSection} onChange={e=>setEditingSection(e.target.value)}><option value="general">General</option><option value="call-center">Call Center</option><option value="door-to-door">Door-to-Door</option><option value="election-day">Election Day</option><option value="transportation">Transportation</option></select><textarea className="field mt-3 min-h-28 py-3" value={editingRemark} onChange={e=>setEditingRemark(e.target.value)} autoFocus/><div className="mt-3 flex flex-wrap justify-end gap-2"><button className="btn-secondary" onClick={cancelEdit}>Cancel</button><button className="btn-primary" disabled={savingEdit} onClick={()=>updateRemark(item)}>{savingEdit?'Saving…':'Save changes'}</button></div></div>:<><div className="mt-2"><span className="status-chip bg-primary-light text-primary">{item.section}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-body">{item.remark}</p><p className="mt-2 text-xs text-body">{item.recorded_by||'Unknown recorder'} · {item.recorded_at?new Date(item.recorded_at).toLocaleString():'—'}</p></>}</article>})}{!visibleItems.length&&<div className="empty-state m-4">No remarks found.</div>}</div></section>
 </div>
}