'use client';
import {useEffect,useMemo,useState} from 'react';
import {getResidentsPage,supabase} from '../lib/supabase';
import type {Resident} from '../lib/types';
import {PartyFilter,ResidentIdentity,matchesParty} from '../shared/ResidentIdentity';

type Remark={id:number|string;resident_id:number|string;section:string;remark:string;recorded_by?:string|null;recorded_at?:string|null};
const sources=['general','call-center','door-to-door','candidate-meeting','election-day','transportation'];
const sourceLabels:Record<string,string>={'general':'General','call-center':'Call Center','door-to-door':'Door-to-Door','candidate-meeting':'Candidate Meeting','election-day':'Election Day','transportation':'Transportation'};
const sourceLabel=(value?:string|null)=>sourceLabels[value||'general']||String(value||'general').replaceAll('-',' ').replace(/^./,x=>x.toUpperCase());
const normalizeResident=(row:any):Resident=>({...row,phone:row.phone==null?null:String(row.phone)} as Resident);

export default function RemarksContent(){
 const [residents,setResidents]=useState<Resident[]>([]),[searchRows,setSearchRows]=useState<Resident[]>([]),[items,setItems]=useState<Remark[]>([]),[query,setQuery]=useState(''),[party,setParty]=useState('all'),[selected,setSelected]=useState(''),[section,setSection]=useState('general'),[sourceFilter,setSourceFilter]=useState('all'),[remark,setRemark]=useState(''),[recordedBy,setRecordedBy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[searching,setSearching]=useState(false);
 const [editingId,setEditingId]=useState<string|null>(null),[editingRemark,setEditingRemark]=useState(''),[editingSection,setEditingSection]=useState('general'),[savingEdit,setSavingEdit]=useState(false);
 async function load(){try{const response=await supabase.from('remarks').select('*').order('recorded_at',{ascending:false}).limit(300);if(response.error)throw response.error;const nextItems=(response.data||[]) as Remark[];setItems(nextItems);const ids=[...new Set(nextItems.map(item=>Number(item.resident_id)).filter(Number.isFinite))];const rows:Resident[]=[];for(let start=0;start<ids.length;start+=500){const residentResponse=await supabase.from('Resident').select('*').in('id',ids.slice(start,start+500));if(residentResponse.error)throw residentResponse.error;rows.push(...(residentResponse.data||[]).map(normalizeResident))}setResidents(rows)}catch(e){setError(e instanceof Error?e.message:'Unable to load remarks')}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const term=query.trim();if(selected||term.length<2){setSearchRows([]);setSearching(false);return}let active=true;setSearching(true);const timer=setTimeout(()=>getResidentsPage({page:1,pageSize:20,search:term,party}).then(result=>{if(active)setSearchRows(result.rows)}).catch(e=>active&&setError(e instanceof Error?e.message:'Resident search failed')).finally(()=>active&&setSearching(false)),250);return()=>{active=false;clearTimeout(timer)}},[query,party,selected]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),residentId=params.get('resident'),requestedSection=params.get('section');if(requestedSection&&sources.includes(requestedSection)){setSection(requestedSection);setSourceFilter(requestedSection)}if(residentId){setSelected(residentId);const resident=residents.find(r=>String(r.id)===residentId);if(resident)setQuery(resident.name||`Resident ${residentId}`)}},[residents]);
 const allResidents=useMemo(()=>{const map=new Map<string,Resident>();[...residents,...searchRows].forEach(r=>map.set(String(r.id),r));return [...map.values()]},[residents,searchRows]);
 const map=useMemo(()=>new Map(allResidents.map(r=>[String(r.id),r])),[allResidents]);
 const matches=useMemo(()=>searchRows.filter(r=>matchesParty(r,party)),[searchRows,party]);
 const visibleItems=useMemo(()=>items.filter(item=>{const resident=map.get(String(item.resident_id));const partyMatch=resident?matchesParty(resident,party):party==='all';const sourceMatch=sourceFilter==='all'||(item.section||'general')===sourceFilter;const text=[resident?.name,resident?.national_id,resident?.phone,resident?.house,item.remark,item.recorded_by,sourceLabel(item.section)].join(' ').toLowerCase();return partyMatch&&sourceMatch&&(!query.trim()||selected||text.includes(query.trim().toLowerCase()))}),[items,map,party,sourceFilter,query,selected]);
 async function save(){if(!selected||!remark.trim()){setError('Select a resident and enter a remark.');return}const session=await supabase.auth.getSession();const recorder=recordedBy.trim()||session.data.session?.user.email||null;const {error}=await supabase.from('remarks').insert({id:Date.now(),resident_id:Number(selected),section,remark:remark.trim(),recorded_by:recorder,recorded_at:new Date().toISOString()});if(error){setError(error.message);return}setError('');setMessage(`Remark saved as ${sourceLabel(section)}.`);setRemark('');load()}
 function beginEdit(item:Remark){setEditingId(String(item.id));setEditingRemark(item.remark);setEditingSection(item.section||'general');setError('');setMessage('')}
 function cancelEdit(){setEditingId(null);setEditingRemark('');setEditingSection('general')}
 async function updateRemark(item:Remark){if(!editingRemark.trim()){setError('Remark cannot be empty.');return}setSavingEdit(true);setError('');const {error}=await supabase.from('remarks').update({remark:editingRemark.trim(),section:editingSection}).eq('id',item.id);setSavingEdit(false);if(error){setError(error.message);return}cancelEdit();setMessage(`Remark updated as ${sourceLabel(editingSection)}.`);load()}
 async function deleteRemark(item:Remark){if(!window.confirm('Delete this remark permanently?'))return;setError('');const {error}=await supabase.from('remarks').delete().eq('id',item.id);if(error){setError(error.message);return}if(editingId===String(item.id))cancelEdit();setMessage('Remark deleted.');load()}
 return <div className="space-y-4">
  <section className="page-hero"><p className="eyebrow">Operational history</p><h1 className="mt-2">Remarks</h1><p className="mt-2 text-sm text-body">Every remark shows where it came from: Call Center, Door-to-Door, Candidate Meeting, Election Day, Transportation or General.</p><div className="mt-4"><PartyFilter value={party} onChange={value=>{setParty(value);setSelected('')}}/></div></section>
  <section className="panel"><div className="grid gap-3 lg:grid-cols-2"><div className="relative"><input className="field" aria-label="Search resident or remark" value={query} onChange={e=>{setQuery(e.target.value);setSelected('')}} placeholder="Search resident or remark"/>{query&&!selected&&<div className="absolute z-20 mt-1 max-h-72 w-full overflow-y-auto rounded-xl border border-border bg-card shadow-card">{searching?<div className="p-3 text-sm text-body">Searching residents…</div>:matches.map(r=><button type="button" key={String(r.id)} className="block w-full border-b border-border p-3 text-left hover:bg-primary-light" onClick={()=>{setSelected(String(r.id));setQuery(r.name||String(r.id));setResidents(current=>current.some(x=>String(x.id)===String(r.id))?current:[r,...current])}}><ResidentIdentity resident={r} compact/></button>)}</div>}</div><select aria-label="Remark source" className="field" value={section} onChange={e=>setSection(e.target.value)}>{sources.map(item=><option key={item} value={item}>{sourceLabel(item)}</option>)}</select><input aria-label="Recorded by" className="field" value={recordedBy} onChange={e=>setRecordedBy(e.target.value)} placeholder="Recorded by (automatic if signed in)"/><textarea aria-label="Remark" className="field min-h-28 py-3" value={remark} onChange={e=>setRemark(e.target.value)} placeholder="Enter a clear operational remark"/></div><div className="mt-3 flex justify-end"><button className="btn-primary" onClick={save}>Save remark</button></div>{message&&<p className="mt-3 text-sm font-semibold text-primary">{message}</p>}{error&&<div className="error-banner mt-3">{error}</div>}</section>
  <section className="panel"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Remark source</p><h2 className="mt-1">Filter operational history</h2></div><select aria-label="Filter remark source" className="field sm:max-w-xs" value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="all">All sources</option>{sources.map(item=><option key={item} value={item}>{sourceLabel(item)}</option>)}</select></div></section>
  <section className="panel overflow-hidden p-0"><div className="divide-y divide-border">{visibleItems.map(item=>{const resident=map.get(String(item.resident_id)),editing=editingId===String(item.id);return <article key={String(item.id)} className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div>{resident?<ResidentIdentity resident={resident}/>:<b>Resident {item.resident_id}</b>}</div>{!editing&&<div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>beginEdit(item)}>Edit</button><button className="btn-secondary text-danger" onClick={()=>deleteRemark(item)}>Delete</button></div>}</div>{editing?<div className="mt-4 rounded-xl border border-primary/30 bg-primary-soft p-4"><label className="block"><span className="field-label">Remark source</span><select className="field" value={editingSection} onChange={e=>setEditingSection(e.target.value)}>{sources.map(source=><option key={source} value={source}>{sourceLabel(source)}</option>)}</select></label><textarea aria-label="Edit remark" className="field mt-3 min-h-28 py-3" value={editingRemark} onChange={e=>setEditingRemark(e.target.value)} autoFocus/><div className="mt-3 flex flex-wrap justify-end gap-2"><button className="btn-secondary" onClick={cancelEdit}>Cancel</button><button className="btn-primary" disabled={savingEdit} onClick={()=>updateRemark(item)}>{savingEdit?'Saving…':'Save changes'}</button></div></div>:<><div className="mt-3 flex flex-wrap items-center gap-2"><span className="status-chip bg-primary-light text-primary">Source: {sourceLabel(item.section)}</span></div><p className="mt-3 whitespace-pre-wrap text-sm text-body">{item.remark}</p><p className="mt-2 text-xs text-body">Recorded by {item.recorded_by||'Unknown recorder'} · {item.recorded_at?new Date(item.recorded_at).toLocaleString():'—'}</p></>}</article>})}{!visibleItems.length&&<div className="empty-state m-4">No remarks found for this source or filter.</div>}</div></section>
 </div>
}