'use client';
import {useEffect,useMemo,useState} from 'react';
import {createWorkflowShare,getElectionBoard,saveTransportation} from '../lib/operations';
import type {Resident} from '../lib/types';

type Row={resident:Resident;election:{resident_id:number|string;reach_status:'reached'|'not-reached';has_voted:boolean;transport_status:string}};
export default function TransportationContent(){
 const [rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('needed'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saved,setSaved]=useState('');
 useEffect(()=>{getElectionBoard().then(data=>setRows(data as Row[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const visible=useMemo(()=>rows.filter(r=>{const match=status==='all'||r.election.transport_status===status;const text=[r.resident.name,r.resident.national_id,r.resident.phone,r.resident.lives_in,r.resident.election_box].join(' ').toLowerCase();return match&&text.includes(query.toLowerCase())}).slice(0,120),[rows,status,query]);
 async function update(row:Row,next:string){setError('');try{await saveTransportation(row.resident.id,{transport_status:next});setRows(current=>current.map(item=>String(item.resident.id)===String(row.resident.id)?{...item,election:{...item.election,transport_status:next}}:item));setSaved('Transportation status saved.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}}
 async function share(){try{const ids=visible.map(r=>Number(r.resident.id));const item=await createWorkflowShare({workflow:'transportation',title:`Transportation · ${status}`,status_filter:status,resident_ids:ids});const url=`${window.location.origin}/Vote/share/?token=${item.token}`;await navigator.clipboard.writeText(url);setSaved('Transportation share link copied.')}catch(e){setError(e instanceof Error?e.message:'Share failed')}}
 return <div className="space-y-4"><section className="page-hero"><p className="eyebrow">Election logistics</p><h1 className="mt-2">Transportation</h1><p className="mt-2 text-sm text-body">Arrange pickup and track residents who need help reaching their election box.</p></section><section className="panel"><div className="grid gap-3 md:grid-cols-[1fr_220px_auto]"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, ID, phone, living place or box"/><select className="field" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All transport statuses</option><option value="not-needed">Not needed</option><option value="needed">Needed</option><option value="requested">Requested</option><option value="assigned">Assigned</option><option value="picked-up">Picked up</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button className="btn-primary" onClick={share}>Copy share link</button></div>{saved&&<p className="mt-3 text-sm font-semibold text-accent">{saved}</p>}{error&&<div className="error-banner mt-3">{error}</div>}</section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{loading?Array.from({length:6}).map((_,i)=><div key={i} className="h-52 animate-pulse bg-primary-light"/>):visible.map(row=><article key={String(row.resident.id)} className="soft-card"><h2 className="text-base">{row.resident.name||'Unnamed resident'}</h2><p className="mt-1 text-xs text-body">{row.resident.national_id||'No ID'} · Box {row.resident.election_box||'—'}</p><dl className="mt-4 grid gap-2 text-sm"><Info label="Mobile" value={row.resident.phone}/><Info label="Living place" value={row.resident.lives_in}/></dl><select className="field mt-4" value={row.election.transport_status} onChange={e=>update(row,e.target.value)}><option value="not-needed">Not needed</option><option value="needed">Needed</option><option value="requested">Requested</option><option value="assigned">Assigned</option><option value="picked-up">Picked up</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></article>)}</section></div>
}
function Info({label,value}:{label:string;value?:string|null}){return <div className="flex justify-between gap-3"><dt className="text-body">{label}</dt><dd className="text-right font-semibold text-navy">{value||'—'}</dd></div>}
