'use client';
import {useEffect,useMemo,useState} from 'react';
import {createWorkflowShare,getElectionBoard,saveTransportation} from '../lib/operations';
import type {Resident} from '../lib/types';
import {PartyFilter,matchesParty} from '../shared/ResidentIdentity';
import {ResidentCard,ResidentFields} from '../shared/ResidentCard';

type Row={resident:Resident;election:{resident_id:number|string;reach_status:'reached'|'not-reached';has_voted:boolean;transport_status:string}};
const statuses=['not-needed','needed','requested','assigned','picked-up','completed','cancelled'];
const label=(value:string)=>value.replaceAll('-',' ').replace(/^./,x=>x.toUpperCase());

export default function TransportationContent(){
 const [rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('needed'),[party,setParty]=useState('all'),[box,setBox]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saved,setSaved]=useState('');
 useEffect(()=>{getElectionBoard().then(data=>setRows(data as Row[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const boxes=useMemo(()=>[...new Set(rows.map(r=>(r.resident.election_box||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>{const statusMatch=status==='all'||r.election.transport_status===status;const boxMatch=box==='all'||r.resident.election_box===box;const text=[r.resident.name,r.resident.national_id,r.resident.phone,r.resident.house,r.resident.lives_in,r.resident.election_box].join(' ').toLowerCase();return matchesParty(r.resident,party)&&statusMatch&&boxMatch&&text.includes(query.toLowerCase())}),[rows,status,query,party,box]);
 const visible=filtered.slice(0,180);
 const boxSummary=useMemo(()=>boxes.map(name=>{const list=rows.filter(r=>r.resident.election_box===name&&matchesParty(r.resident,party));return {name,total:list.length,needed:list.filter(r=>r.election.transport_status==='needed'||r.election.transport_status==='requested').length,assigned:list.filter(r=>r.election.transport_status==='assigned').length,picked:list.filter(r=>r.election.transport_status==='picked-up').length,completed:list.filter(r=>r.election.transport_status==='completed').length}}),[rows,boxes,party]);
 const selectedSummary=box==='all'?null:boxSummary.find(item=>item.name===box)||null;
 async function update(row:Row,next:string){setError('');try{await saveTransportation(row.resident.id,{transport_status:next});setRows(current=>current.map(item=>String(item.resident.id)===String(row.resident.id)?{...item,election:{...item.election,transport_status:next}}:item));setSaved('Transportation status saved.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}}
 async function share(){try{const ids=filtered.map(r=>Number(r.resident.id));const title=`${party==='all'?'All parties':party} · ${box==='all'?'All boxes':`Box ${box}`} · ${label(status)}`;const item=await createWorkflowShare({workflow:'transportation',title,status_filter:status,resident_ids:ids});await navigator.clipboard.writeText(`${window.location.origin}/Vote/share/?token=${item.token}`);setSaved('Transportation share link copied.')}catch(e){setError(e instanceof Error?e.message:'Share failed')}}
 return <div className="space-y-4">
  <section className="page-hero"><p className="eyebrow">Election logistics</p><h1 className="mt-2">Transportation</h1><div className="mt-4"><PartyFilter value={party} onChange={setParty}/></div></section>
  <section className="panel"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[1fr_240px_220px_auto]"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, ID, mobile or address"/><select className="field" value={box} onChange={e=>setBox(e.target.value)}><option value="all">All election boxes</option>{boxes.map(item=><option key={item} value={item}>Box {item}</option>)}</select><select className="field" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All transport statuses</option>{statuses.map(item=><option key={item} value={item}>{label(item)}</option>)}</select><button className="btn-primary" onClick={share}>Copy share link</button></div>{selectedSummary&&<div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Summary label="Residents" value={selectedSummary.total}/><Summary label="Need" value={selectedSummary.needed}/><Summary label="Assigned" value={selectedSummary.assigned}/><Summary label="Picked up" value={selectedSummary.picked}/><Summary label="Completed" value={selectedSummary.completed}/></div>}<div className="mt-3 text-sm text-body"><b className="text-navy">{filtered.length.toLocaleString()} residents</b> · {box==='all'?'All election boxes':`Box ${box}`} · {party==='all'?'All parties':party}</div>{saved&&<p className="mt-3 text-sm font-semibold text-accent">{saved}</p>}{error&&<div className="error-banner mt-3">{error}</div>}</section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{loading?Array.from({length:6}).map((_,i)=><div key={i} className="h-64 animate-pulse rounded-card bg-primary-light"/>):visible.map(row=><ResidentCard key={String(row.resident.id)} resident={row.resident} actions={<select className="field" value={row.election.transport_status} onChange={e=>update(row,e.target.value)}>{statuses.map(item=><option key={item} value={item}>{label(item)}</option>)}</select>}><ResidentFields resident={row.resident}/></ResidentCard>)}</section>
  {!loading&&!visible.length&&<div className="empty-state">No residents match the selected filters.</div>}
 </div>
}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-border bg-slate-50 p-3"><span className="text-xs text-body">{label}</span><b className="mt-1 block text-xl text-navy">{value}</b></div>}
