'use client';
import {FormEvent,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Role='admin'|'supervisor'|'call_agent'|'field_agent'|'election_operator'|'viewer';
type ManagedUser={id:string;email:string;username?:string;name:string;role:Role;active:boolean;created_at?:string;last_sign_in_at?:string|null};
const roles:Role[]=['admin','supervisor','call_agent','field_agent','election_operator','viewer'];
const label=(role:Role)=>role.replace(/_/g,' ').replace(/\b\w/g,char=>char.toUpperCase());

export default function UserManagementContent(){
 const [users,setUsers]=useState<ManagedUser[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState<Role>('viewer');
 async function request(body:Record<string,unknown>){const {data,error}=await supabase.functions.invoke('manage-users',{body});if(error)throw new Error(error.message);if(data?.error)throw new Error(data.error);return data}
 async function load(){setLoading(true);setError('');try{const data=await request({action:'list'});setUsers(data.users||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load users')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();setBusy('create');setError('');setMessage('');try{await request({action:'create',name,username,password,role});setName('');setUsername('');setPassword('');setRole('viewer');setMessage('User account created.');await load()}catch(e){setError(e instanceof Error?e.message:'User creation failed')}finally{setBusy('')}}
 async function changeRole(user:ManagedUser,next:Role){setBusy(user.id);setError('');try{await request({action:'set_role',user_id:user.id,role:next});setMessage(`${user.email} role updated.`);await load()}catch(e){setError(e instanceof Error?e.message:'Role update failed')}finally{setBusy('')}}
 async function toggle(user:ManagedUser){setBusy(user.id);setError('');try{await request({action:'set_active',user_id:user.id,active:!user.active});setMessage(`${user.email} is now ${user.active?'disabled':'active'}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Account update failed')}finally{setBusy('')}}
 async function resetPassword(user:ManagedUser){const next=window.prompt(`Set a new password for ${user.email} (minimum 8 characters):`);if(!next)return;setBusy(user.id);setError('');try{await request({action:'set_password',user_id:user.id,password:next});setMessage(`Password changed for ${user.email}.`)}catch(e){setError(e instanceof Error?e.message:'Password change failed')}finally{setBusy('')}}
 return <div className="space-y-4">
  <section className="page-hero"><p className="eyebrow">Admin control</p><h1 className="mt-2">User Management</h1><p className="mt-2 text-sm text-body">Create staff accounts, set their access role, change passwords, or disable access.</p></section>
  <section className="panel"><div className="section-heading"><div><p className="eyebrow">New staff account</p><h2 className="mt-1">Create user</h2></div></div><form onSubmit={create} className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/><input className="field" value={username} onChange={e=>setUsername(e.target.value)} required minLength={3} maxLength={32} autoComplete="username" placeholder="Username"/><input className="field" value={password} onChange={e=>setPassword(e.target.value)} type="password" required minLength={8} placeholder="Temporary password"/><select className="field" value={role} onChange={e=>setRole(e.target.value as Role)}>{roles.map(item=><option key={item} value={item}>{label(item)}</option>)}</select><button className="btn-primary" disabled={busy==='create'}>{busy==='create'?'Creating…':'Create user'}</button></form><p className="mt-3 text-xs text-body">Username: 3–32 letters, numbers, dots, dashes, or underscores. Password must be at least 8 characters.</p></section>
  {message&&<div className="info-banner">{message}</div>}{error&&<div className="error-banner">{error}</div>}
  <section className="panel overflow-hidden p-0"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="eyebrow">Staff accounts</p><h2 className="mt-1">{users.length} users</h2></div><button className="btn-secondary" onClick={load} disabled={loading}>Refresh</button></div>
   {loading?<div className="p-5"><div className="h-32 animate-pulse rounded-xl bg-primary-light"/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-primary-light"><tr><th className="p-4">User</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Last sign-in</th><th className="p-4">Actions</th></tr></thead><tbody>{users.map(user=><tr key={user.id} className="border-t border-border"><td className="p-4"><b className="block text-navy">{user.name||'Unnamed user'}</b><span className="text-body">{user.username||user.email}</span></td><td className="p-4"><select className="field min-w-40" value={user.role} disabled={busy===user.id} onChange={e=>changeRole(user,e.target.value as Role)}>{roles.map(item=><option key={item} value={item}>{label(item)}</option>)}</select></td><td className="p-4"><span className={`status-chip ${user.active?'status-success':'bg-slate-100 text-slate-500'}`}>{user.active?'Active':'Disabled'}</span></td><td className="p-4 text-body">{user.last_sign_in_at?new Date(user.last_sign_in_at).toLocaleString():'Never'}</td><td className="p-4"><div className="flex gap-2"><button className="btn-secondary" disabled={busy===user.id} onClick={()=>resetPassword(user)}>Password</button><button className={user.active?'btn-secondary text-danger':'btn-success'} disabled={busy===user.id} onClick={()=>toggle(user)}>{user.active?'Disable':'Enable'}</button></div></td></tr>)}</tbody></table></div>}</section>
 </div>
}