'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {getResidentById,updateResident} from '../lib/supabase';
import type {Resident} from '../lib/types';
import StatusBadge from '../shared/StatusBadge';

const tabs=['Overview','Call Center','Door-to-Door','Candidate Visit','Election Day','Remarks'];
const editableFields:(keyof Resident)[]=['name','national_id','house','lives_in','phone','vote_status','phone_status','reach_status','d2d_status','support_level','remarks'];

export default function VoterDetailContent(){
 const params=useSearchParams();const id=params.get('id');
 const [resident,setResident]=useState<Resident|null>(null);const [draft,setDraft]=useState<Partial<Resident>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [active,setActive]=useState('Overview');const [saving,setSaving]=useState(false);const [saved,setSaved]=useState('');
 useEffect(()=>{let mounted=true;setSaved('');setError('');if(!id){setResident(null);setDraft({});setLoading(false);return()=>{mounted=false}}setLoading(true);getResidentById(id).then(data=>{if(mounted){setResident(data);setDraft(data)}}).catch(e=>{if(mounted)setError(e instanceof Error?e.message:'Unable to load voter')}).finally(()=>{if(mounted)setLoading(false)});return()=>{mounted=false}},[id]);
 const changes=useMemo(()=>{if(!resident)return{};const next:Partial<Resident>={};for(const field of editableFields){const before=resident[field]??null;const after=draft[field]??null;if(before!==after)(next as any)[field]=after}return next},[resident,draft]);
 const dirty=Object.keys(changes).length>0;
 async function save(){if(!resident||!dirty||saving)return;setSaving(true);setSaved('');setError('');try{const updated=await updateResident(resident.id,changes);setResident(updated);setDraft(updated);setSaved('Changes saved successfully.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}
 function reset(){if(resident){setDraft(resident);setError('');setSaved('Changes discarded.')}}
 if(!id)return <div className="panel text-center"><h1 className="text-2xl font-bold">Select a voter first</h1><Link prefetch={false} href="/voter-management/" className="action mt-5 bg-[#0F8B8D] text-white">Open Residents</Link></div>;
 if(error&&!resident)return <div className="panel text-rose-700">{error}</div>;
 if(!resident)return <div className="panel" aria-busy={loading}><div className="h-40 animate-pulse rounded-2xl bg-slate-100"/></div>;
 return <div className="space-y-5">
  <section className="rounded-3xl bg-gradient-to-br from-[#17324D] to-[#0F5960] p-5 text-white md:p-7"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-center gap-4">{resident.photo_url?<img src={resident.photo_url} alt="Resident" className="h-20 w-20 rounded-2xl border border-white/20 object-cover"/>:<div className="grid h-20 w-20 place-items-center rounded-2xl bg-white/10 text-xl font-bold">{(resident.name||'?').slice(0,2).toUpperCase()}</div>}<div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-100">Resident profile</p><h1 className="mt-1 text-2xl font-extrabold md:text-3xl">{resident.name||'Unnamed resident'}</h1><p className="mt-2 text-sm text-slate-200">{resident.national_id||'No ID'} · {resident.house||'No official house'}</p></div></div><div className="flex flex-wrap gap-2"><StatusBadge status={draft.vote_status}/><StatusBadge status={draft.phone_status}/><StatusBadge status={draft.d2d_status}/></div></div></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Snapshot label="Official house" value={draft.house}/><Snapshot label="Living now" value={draft.lives_in}/><Snapshot label="Mobile" value={draft.phone}/><Snapshot label="Party" value={resident.party}/></section>
  {draft.remarks&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-extrabold uppercase tracking-wide text-amber-700">Important remarks before contact</p><p className="mt-2 whitespace-pre-wrap text-sm font-semibold text-slate-800">{draft.remarks}</p></section>}
  <div role="tablist" className="flex gap-2 overflow-x-auto pb-1">{tabs.map(t=><button key={t} onClick={()=>setActive(t)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-semibold ${active===t?'bg-[#0F8B8D] text-white':'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{t}</button>)}</div>
  <section className="panel space-y-5"><h2 className="section-title">{active}</h2>
   {active==='Overview'&&<ContactFields draft={draft} setDraft={setDraft}/>} 
   {active==='Call Center'&&<div className="space-y-5"><ContactFields draft={draft} setDraft={setDraft}/><div className="grid gap-4 md:grid-cols-2"><Select label="Phone status" value={draft.phone_status||'need-call'} options={['need-call','called']} onChange={v=>setDraft({...draft,phone_status:v as Resident['phone_status']})}/><Select label="Reach status" value={draft.reach_status||'not-reached'} options={['not-reached','reached']} onChange={v=>setDraft({...draft,reach_status:v as Resident['reach_status']})}/></div><RemarksField draft={draft} setDraft={setDraft}/></div>}
   {active==='Door-to-Door'&&<div className="space-y-5"><ContactFields draft={draft} setDraft={setDraft}/><Select label="Visit result" value={draft.d2d_status||'not-visited'} options={['not-visited','reach','not-home','live-in-another-place']} onChange={v=>setDraft({...draft,d2d_status:v as Resident['d2d_status']})}/><RemarksField draft={draft} setDraft={setDraft}/></div>}
   {active==='Candidate Visit'&&<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><Snapshot label="Name" value={draft.name}/><Snapshot label="National ID" value={draft.national_id}/><Snapshot label="Official house" value={draft.house}/><Snapshot label="Living now" value={draft.lives_in}/><Snapshot label="Mobile" value={draft.phone}/><Snapshot label="Party" value={resident.party}/></div><Select label="Support level" value={draft.support_level||'not-guaranteed'} options={['not-guaranteed','guaranteed']} onChange={v=>setDraft({...draft,support_level:v as Resident['support_level']})}/><RemarksField draft={draft} setDraft={setDraft}/></div>}
   {active==='Election Day'&&<Select label="Vote intention" value={draft.vote_status||'not-decided'} options={['not-decided','will-vote','not-vote']} onChange={v=>setDraft({...draft,vote_status:v as Resident['vote_status']})}/>} 
   {active==='Remarks'&&<RemarksField draft={draft} setDraft={setDraft}/>} 
   <div className="sticky bottom-3 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div>{saved&&<span className="text-sm text-emerald-700">{saved}</span>}{error&&<span className="text-sm text-rose-700">{error}</span>}{dirty&&!saved&&!error&&<span className="text-sm text-amber-700">Unsaved changes</span>}</div><div className="flex gap-2"><button className="action border border-slate-200 bg-white text-slate-700" onClick={reset} disabled={!dirty||saving}>Discard</button><button className="action flex-1 bg-[#0F8B8D] text-white sm:flex-none" onClick={save} disabled={!dirty||saving}>{saving?'Saving…':'Save update'}</button></div></div>
  </section>
 </div>;
}
function ContactFields({draft,setDraft}:{draft:Partial<Resident>,setDraft:(d:Partial<Resident>)=>void}){return <div className="grid gap-4 md:grid-cols-2"><Field label="Name" value={draft.name||''} onChange={v=>setDraft({...draft,name:v})}/><Field label="National ID" value={draft.national_id||''} onChange={v=>setDraft({...draft,national_id:v})}/><Field label="Official house" value={draft.house||''} onChange={v=>setDraft({...draft,house:v})}/><Field label="Living now" value={draft.lives_in||''} onChange={v=>setDraft({...draft,lives_in:v})}/><Field label="Mobile" value={draft.phone||''} onChange={v=>setDraft({...draft,phone:v})}/></div>}
function RemarksField({draft,setDraft}:{draft:Partial<Resident>,setDraft:(d:Partial<Resident>)=>void}){return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-800">Important remarks</span><p className="mb-2 text-xs text-slate-500">Record access notes, preferred contact time, current location, family information, or anything the next staff member must know.</p><textarea className="field min-h-36 py-3" value={draft.remarks||''} onChange={e=>setDraft({...draft,remarks:e.target.value})} placeholder="Add a clear operational remark…"/></label>}
function Snapshot({label,value}:{label:string,value?:string|null}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 break-words font-bold text-slate-800">{value||'Not recorded'}</p></div>}
function Field({label,value,onChange}:{label:string,value:string,onChange:(v:string)=>void}){return <label><span className="mb-2 block text-sm font-semibold">{label}</span><input className="field" value={value} onChange={e=>onChange(e.target.value)} autoComplete="off"/></label>}
function Select({label,value,options,onChange}:{label:string,value:string,options:string[],onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><select className="field" value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{o.replaceAll('-',' ')}</option>)}</select></label>}