'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {getResidentById,submitResidentContactChange,updateResident} from '../lib/supabase';
import type {Resident} from '../lib/types';
import {VOTER_DETAIL_TABS,residentInitials} from '../lib/voterConstants';
import StatusBadge from '../shared/StatusBadge';

const operationalFields:(keyof Resident)[]=['vote_status','phone_status','reach_status','d2d_status','support_level','remarks'];

export default function VoterDetailContent(){
 const params=useSearchParams(),id=params.get('id');
 const [resident,setResident]=useState<Resident|null>(null),[draft,setDraft]=useState<Partial<Resident>>({}),[requestedPhone,setRequestedPhone]=useState(''),[requestedLiving,setRequestedLiving]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[active,setActive]=useState('Overview'),[saving,setSaving]=useState(false),[saved,setSaved]=useState('');
 useEffect(()=>{let mounted=true;setSaved('');setError('');if(!id){setResident(null);setLoading(false);return()=>{mounted=false}}setLoading(true);getResidentById(id).then(data=>{if(mounted){setResident(data);setDraft(data);setRequestedPhone(data.phone||'');setRequestedLiving(data.lives_in||'')}}).catch(e=>{if(mounted)setError(e instanceof Error?e.message:'Unable to load voter')}).finally(()=>{if(mounted)setLoading(false)});return()=>{mounted=false}},[id]);
 const changes=useMemo(()=>{if(!resident)return{};const next:Partial<Resident>={};for(const field of operationalFields){if((resident[field]??null)!==(draft[field]??null))(next as any)[field]=draft[field]??null}return next},[resident,draft]);
 const contactChanged=Boolean(resident&&(requestedPhone.trim()!==(resident.phone||'').trim()||requestedLiving.trim()!==(resident.lives_in||'').trim()));
 const dirty=Object.keys(changes).length>0||contactChanged;
 async function save(){if(!resident||!dirty||saving)return;setSaving(true);setSaved('');setError('');try{let updated=resident;if(Object.keys(changes).length)updated=await updateResident(resident.id,changes);if(contactChanged)await submitResidentContactChange(resident,{phone:requestedPhone,lives_in:requestedLiving,remarks:draft.remarks});setResident(updated);setDraft(updated);setRequestedPhone(updated.phone||'');setRequestedLiving(updated.lives_in||'');setSaved(contactChanged?'Update submitted for admin verification. Campaign statuses were saved.':'Campaign update saved.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}
 function reset(){if(resident){setDraft(resident);setRequestedPhone(resident.phone||'');setRequestedLiving(resident.lives_in||'');setError('');setSaved('Changes discarded.')}}
 if(!id)return <div className="panel text-center"><h1>Select a voter first</h1><Link prefetch={false} href="/voter-management/" className="btn-primary mt-5">Open Residents</Link></div>;
 if(error&&!resident)return <div className="panel text-danger">{error}</div>;
 if(!resident)return <div className="panel" aria-busy={loading}><div className="h-32 animate-pulse rounded-card bg-primary-light"/></div>;
 return <div className="space-y-4 pb-6">
  <section className="brand-card overflow-hidden p-0">
   <div className="border-l-4 border-primary px-5 py-5 sm:px-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
     <div className="flex min-w-0 items-center gap-4">{resident.photo_url?<img src={resident.photo_url} alt="Resident" className="h-16 w-16 shrink-0 rounded-card border border-border object-cover md:h-20 md:w-20"/>:<div className="grid h-16 w-16 shrink-0 place-items-center rounded-card bg-primary-light text-lg font-bold text-primary md:h-20 md:w-20">{residentInitials(resident.name)}</div>}<div className="min-w-0"><p className="eyebrow">Verified resident record</p><h1 className="mt-1 truncate">{resident.name||'Unnamed resident'}</h1><p className="mt-1 truncate text-sm text-body">{resident.national_id||'No ID'} · {resident.house||'No official house'}</p></div></div>
     <div className="flex flex-wrap gap-2"><StatusBadge status={draft.vote_status}/><StatusBadge status={draft.phone_status}/><StatusBadge status={draft.d2d_status}/></div>
    </div>
   </div>
  </section>
  <section className="info-banner"><span className="info-icon">i</span><div><p className="font-semibold text-navy">Verified identity is protected</p><p className="mt-0.5 text-xs leading-5 text-body sm:text-sm">Field users may submit only a new mobile number or current living place for admin approval. Identity fields remain read-only.</p></div></section>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Snapshot label="Official house" value={resident.house}/><Snapshot label="Living now" value={resident.lives_in}/><Snapshot label="Verified mobile" value={resident.phone}/><Snapshot label="Party" value={resident.party}/></section>
  {draft.remarks&&<section className="notice-card"><p className="eyebrow">Important remarks before contact</p><p className="mt-1 whitespace-pre-wrap text-sm font-medium text-navy">{draft.remarks}</p></section>}
  <div role="tablist" className="tab-bar">{VOTER_DETAIL_TABS.map(t=><button key={t} onClick={()=>setActive(t)} className={`tab-pill ${active===t?'tab-pill-active':''}`}>{t}</button>)}</div>
  <section className="panel space-y-5"><h2>{active}</h2>
   {active==='Overview'&&<div className="space-y-5"><VerifiedFields resident={resident}/><PendingContactFields phone={requestedPhone} living={requestedLiving} setPhone={setRequestedPhone} setLiving={setRequestedLiving}/></div>}
   {active==='Call Center'&&<div className="space-y-5"><VerifiedFields resident={resident}/><PendingContactFields phone={requestedPhone} living={requestedLiving} setPhone={setRequestedPhone} setLiving={setRequestedLiving}/><div className="grid gap-4 md:grid-cols-2"><Select label="Phone status" value={draft.phone_status||'need-call'} options={['need-call','called']} onChange={v=>setDraft({...draft,phone_status:v as Resident['phone_status']})}/><Select label="Reach status" value={draft.reach_status||'not-reached'} options={['not-reached','reached']} onChange={v=>setDraft({...draft,reach_status:v as Resident['reach_status']})}/></div><RemarksField draft={draft} setDraft={setDraft}/></div>}
   {active==='Door-to-Door'&&<div className="space-y-5"><VerifiedFields resident={resident}/><PendingContactFields phone={requestedPhone} living={requestedLiving} setPhone={setRequestedPhone} setLiving={setRequestedLiving}/><Select label="Visit result" value={draft.d2d_status||'not-visited'} options={['not-visited','reach','not-home','live-in-another-place']} onChange={v=>setDraft({...draft,d2d_status:v as Resident['d2d_status']})}/><RemarksField draft={draft} setDraft={setDraft}/></div>}
   {active==='Candidate Visit'&&<div className="space-y-5"><VerifiedFields resident={resident}/><Select label="Support level" value={draft.support_level||'not-guaranteed'} options={['not-guaranteed','guaranteed']} onChange={v=>setDraft({...draft,support_level:v as Resident['support_level']})}/><RemarksField draft={draft} setDraft={setDraft}/></div>}
   {active==='Election Day'&&<Select label="Vote intention" value={draft.vote_status||'not-decided'} options={['not-decided','will-vote','not-vote']} onChange={v=>setDraft({...draft,vote_status:v as Resident['vote_status']})}/>} 
   {active==='Remarks'&&<RemarksField draft={draft} setDraft={setDraft}/>} 
   <div className="flex flex-col gap-3 border-t border-border pt-5 sm:flex-row sm:items-center sm:justify-between"><div className="min-h-5">{saved&&<span className="text-sm text-accent">{saved}</span>}{error&&<span className="text-sm text-danger">{error}</span>}{dirty&&!saved&&!error&&<span className="text-sm text-warning">Unsaved changes</span>}</div><div className="flex gap-2"><button className="btn-secondary" onClick={reset} disabled={!dirty||saving}>Discard</button><button className="btn-primary flex-1 sm:flex-none" onClick={save} disabled={!dirty||saving}>{saving?'Saving…':contactChanged?'Submit for verification':'Save update'}</button></div></div>
  </section>
 </div>;
}
function VerifiedFields({resident}:{resident:Resident}){return <div><p className="eyebrow mb-3">Verified database information</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Snapshot label="Name" value={resident.name}/><Snapshot label="National ID" value={resident.national_id}/><Snapshot label="Official house" value={resident.house}/><Snapshot label="Existing mobile" value={resident.phone}/><Snapshot label="Living now" value={resident.lives_in}/><Snapshot label="Party" value={resident.party}/></div></div>}
function PendingContactFields({phone,living,setPhone,setLiving}:{phone:string;living:string;setPhone:(v:string)=>void;setLiving:(v:string)=>void}){return <div className="info-banner block"><p className="font-bold text-navy">Submit corrected contact information</p><p className="mt-1 text-xs text-body">These values stay pending until an admin verifies and approves them.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="New mobile number" value={phone} onChange={setPhone}/><Field label="Current living place" value={living} onChange={setLiving}/></div></div>}
function RemarksField({draft,setDraft}:{draft:Partial<Resident>,setDraft:(d:Partial<Resident>)=>void}){return <label className="block"><span className="mb-2 block text-sm font-bold text-navy">Important remarks</span><p className="mb-2 text-xs text-body">Record access notes, preferred contact time, location details, family information, or anything the next staff member must know.</p><textarea className="field min-h-36 py-3" value={draft.remarks||''} onChange={e=>setDraft({...draft,remarks:e.target.value})} placeholder="Add a clear operational remark…"/></label>}
function Snapshot({label,value}:{label:string,value?:string|null}){return <div className="brand-card p-4"><p className="eyebrow">{label}</p><p className="mt-1.5 break-words font-bold text-navy">{value||'Not recorded'}</p></div>}
function Field({label,value,onChange}:{label:string,value:string,onChange:(v:string)=>void}){return <label><span className="mb-2 block text-sm font-semibold text-navy">{label}</span><input className="field" value={value} onChange={e=>onChange(e.target.value)} autoComplete="off"/></label>}
function Select({label,value,options,onChange}:{label:string,value:string,options:string[],onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-navy">{label}</span><select className="field" value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{o.replaceAll('-',' ')}</option>)}</select></label>}
