'use client';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import {getHouseOptions,getPartyOptions,getResidentsPage} from '../lib/supabase';
import type {HouseOption,PartyOption} from '../lib/supabase';
import type {Resident} from '../lib/types';
import StatusBadge from '../shared/StatusBadge';

const PAGE_SIZE=25;
type ViewMode='list'|'gallery';

export default function VoterManagementContent(){
 const [rows,setRows]=useState<Resident[]>([]);const [houses,setHouses]=useState<HouseOption[]>([]);const [parties,setParties]=useState<PartyOption[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [debouncedQuery,setDebouncedQuery]=useState('');const [filter,setFilter]=useState('all');const [house,setHouse]=useState('all');const [party,setParty]=useState('all');const [page,setPage]=useState(1);const [count,setCount]=useState(0);const [view,setView]=useState<ViewMode>('list');
 useEffect(()=>{getHouseOptions().then(setHouses).catch(()=>setHouses([]));getPartyOptions().then(setParties).catch(()=>setParties([]))},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedQuery(query),300);return()=>window.clearTimeout(timer)},[query]);
 useEffect(()=>setPage(1),[debouncedQuery,filter,house,party]);
 useEffect(()=>{let active=true;setLoading(true);setError('');getResidentsPage({page,pageSize:PAGE_SIZE,search:debouncedQuery,filter,house,party}).then(result=>{if(active){setRows(result.rows);setCount(result.count)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load residents')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[page,debouncedQuery,filter,house,party]);
 const pages=Math.max(1,Math.ceil(count/PAGE_SIZE));
 const range=useMemo(()=>{if(count===0)return'0';const start=(page-1)*PAGE_SIZE+1;const end=Math.min(page*PAGE_SIZE,count);return`${start.toLocaleString()}–${end.toLocaleString()}`},[page,count]);
 const selectedParty=parties.find(item=>item.name===party);const hasFilters=Boolean(query||filter!=='all'||house!=='all'||party!=='all');
 function clearFilters(){setQuery('');setFilter('all');setHouse('all');setParty('all')}
 return <div className="space-y-4">
  <section className="rounded-card bg-gradient-to-br from-[#17324D] via-[#183B57] to-[#0F5960] px-5 py-5 text-white shadow-card sm:px-6">
   <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-teal-100">Campaign operations</p><h1 className="mt-1 text-3xl font-extrabold text-white">Residents</h1><p className="mt-1 max-w-2xl text-sm text-slate-200">Find residents quickly and update campaign work.</p></div><div className="flex gap-2"><Metric label="Results" value={count.toLocaleString()}/><Metric label="Houses" value={houses.length.toLocaleString()}/></div></div>
  </section>
  <section className="panel overflow-visible p-4 sm:p-5">
   <div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-[minmax(260px,1fr)_minmax(240px,.9fr)_180px_210px]">
    <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Search resident</span><div className="relative"><span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">⌕</span><input className="field pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, ID, phone or address" autoComplete="off"/></div></label>
    <HousePicker houses={houses} value={house} onChange={setHouse}/>
    <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Party</span><select className="field" value={party} onChange={e=>setParty(e.target.value)}><option value="all">All parties</option>{parties.map(item=><option key={item.name} value={item.name}>{item.name} ({item.count})</option>)}</select>{selectedParty&&<span className="mt-1 block text-xs font-semibold text-teal-700">{selectedParty.count} residents</span>}</label>
    <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Campaign status</span><select className="field" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="will-vote">Will vote</option><option value="not-decided">Not decided</option><option value="not-vote">Not voting</option><option value="need-call">Need call</option><option value="called">Called</option><option value="not-visited">Not visited</option><option value="reach">Visited / reached</option><option value="guaranteed">Guaranteed</option></select></label>
   </div>
   <div className="mt-4 flex flex-col gap-3 border-t border-border pt-4 sm:flex-row sm:items-center sm:justify-between">
    <div className="flex flex-wrap gap-2">{party!=='all'&&<FilterChip label={`Party: ${party}`} onClear={()=>setParty('all')}/>} {house!=='all'&&<FilterChip label={`House: ${house}`} onClear={()=>setHouse('all')}/>} {filter!=='all'&&<FilterChip label={filter.replaceAll('-',' ')} onClear={()=>setFilter('all')}/>}</div>
    <div className="flex items-center gap-2"><div className="flex rounded-pill border border-border bg-primary-light p-1"><button type="button" onClick={()=>setView('list')} className={`rounded-pill px-4 py-2 text-xs font-bold ${view==='list'?'bg-white text-primary shadow-card':'text-body'}`}>List</button><button type="button" onClick={()=>setView('gallery')} className={`rounded-pill px-4 py-2 text-xs font-bold ${view==='gallery'?'bg-white text-primary shadow-card':'text-body'}`}>Gallery</button></div><button type="button" className="btn-secondary whitespace-nowrap" onClick={clearFilters} disabled={!hasFilters}>Clear filters</button></div>
   </div>
  </section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><PartySummary label="All parties" value={parties.reduce((sum,item)=>sum+item.count,0)} active={party==='all'} onClick={()=>setParty('all')}/>{parties.map(item=><PartySummary key={item.name} label={item.name} value={item.count} active={party===item.name} onClick={()=>setParty(item.name)}/>)}</section>
  {error&&<div role="alert" className="error-banner">{error}</div>}
  <section className="panel overflow-hidden p-0"><div className="flex flex-col justify-between gap-2 border-b border-border px-5 py-4 sm:flex-row sm:items-center"><div><h2 className="font-bold text-navy">Resident directory</h2><p className="text-sm text-body">Showing {range} of {count.toLocaleString()}</p></div><span className="text-xs font-semibold text-body">Page {page} of {pages}</span></div>
   {view==='list'?<ListView rows={rows} loading={loading}/>:<GalleryView rows={rows} loading={loading}/>}<div className="flex items-center justify-between border-t border-border bg-primary-light px-5 py-4"><span className="text-sm text-body">{count.toLocaleString()} residents</span><div className="flex gap-2"><button className="btn-secondary" disabled={loading||page===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><button className="btn-primary" disabled={loading||page>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Next</button></div></div>
  </section>
 </div>
}

function HousePicker({houses,value,onChange}:{houses:HouseOption[];value:string;onChange:(value:string)=>void}){
 const [open,setOpen]=useState(false);const [search,setSearch]=useState('');const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{function close(e:MouseEvent){if(root.current&&!root.current.contains(e.target as Node))setOpen(false)}document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 const filtered=useMemo(()=>houses.filter(h=>h.name.toLowerCase().includes(search.trim().toLowerCase())).slice(0,100),[houses,search]);const selected=houses.find(h=>h.name===value);function choose(next:string){onChange(next);setSearch('');setOpen(false)}
 return <div ref={root} className="relative"><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">House</span><button type="button" onClick={()=>setOpen(v=>!v)} className="flex min-h-11 w-full items-center justify-between rounded-card border border-border bg-white px-3 text-left text-sm shadow-sm"><span className="min-w-0"><span className="block truncate font-bold text-navy">{selected?.name||'All houses'}</span><span className="block text-xs text-body">{selected?`${selected.count} residents`:`${houses.length} houses available`}</span></span><span>⌄</span></button>{open&&<div className="absolute z-50 mt-2 w-full min-w-[280px] overflow-hidden rounded-card border border-border bg-white shadow-card"><div className="border-b border-border p-3"><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} className="field" placeholder="Search house..."/></div><div className="max-h-80 overflow-y-auto p-2"><button type="button" onClick={()=>choose('all')} className="w-full rounded-card px-3 py-3 text-left font-bold hover:bg-primary-light">All houses</button>{filtered.map(item=><button type="button" key={item.name} onClick={()=>choose(item.name)} className="mt-1 flex w-full items-center justify-between rounded-card px-3 py-3 text-left hover:bg-primary-light"><span className="truncate font-bold">{item.name}</span><span className="status-chip bg-primary-light text-body">{item.count}</span></button>)}</div></div>}</div>
}

function ListView({rows,loading}:{rows:Resident[];loading:boolean}){return <div className="overflow-x-auto" aria-busy={loading}><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-primary-light"><tr className="border-b border-border text-[11px] uppercase tracking-[.12em] text-body"><th className="p-4">Resident</th><th className="p-4">National ID</th><th className="p-4">Official address</th><th className="p-4">Phone</th><th className="p-4">Party</th><th className="p-4">Vote</th><th className="p-4">Call</th><th className="p-4">Visit</th></tr></thead><tbody>{loading?Array.from({length:7}).map((_,i)=><tr key={i}><td colSpan={8} className="p-4"><div className="h-12 animate-pulse rounded-card bg-primary-light"/></td></tr>):rows.length?rows.map(r=><tr key={String(r.id)} className="border-b border-border transition hover:bg-primary-light"><td className="p-4"><div className="flex items-center gap-3"><ResidentPhoto resident={r}/><div className="min-w-0"><Link prefetch={false} href={`/voter-detail/?id=${encodeURIComponent(String(r.id))}`} className="block truncate font-bold text-navy hover:text-primary">{r.name||'Unnamed resident'}</Link><div className="truncate text-xs text-body">{r.lives_in||'Living address not recorded'}</div></div></div></td><td className="p-4 text-body">{r.national_id||'—'}</td><td className="p-4 text-body">{r.house||'—'}</td><td className="p-4 text-body">{r.phone||'—'}</td><td className="p-4"><PartyBadge party={r.party}/></td><td className="p-4"><StatusBadge status={r.vote_status}/></td><td className="p-4"><StatusBadge status={r.phone_status}/></td><td className="p-4"><StatusBadge status={r.d2d_status}/></td></tr>):<tr><td colSpan={8} className="p-14 text-center text-body">No residents found.</td></tr>}</tbody></table></div>}
function GalleryView({rows,loading}:{rows:Resident[];loading:boolean}){if(loading)return <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="h-56 animate-pulse rounded-card bg-primary-light"/>)}</div>;if(!rows.length)return <div className="p-14 text-center text-body">No residents found.</div>;return <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{rows.map(r=><article key={String(r.id)} className="brand-card p-5"><div className="flex items-start gap-4"><ResidentPhoto resident={r} large/><div className="min-w-0"><Link prefetch={false} href={`/voter-detail/?id=${encodeURIComponent(String(r.id))}`} className="block truncate text-lg font-extrabold text-navy hover:text-primary">{r.name||'Unnamed resident'}</Link><p className="mt-1 text-sm text-body">{r.national_id||'No ID'}</p><p className="mt-2 text-sm font-semibold text-navy">{r.house||'No official address'}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><PartyBadge party={r.party}/><StatusBadge status={r.vote_status}/><StatusBadge status={r.phone_status}/></div></article>)}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="min-w-24 rounded-card border border-white/15 bg-white/10 px-4 py-3"><div className="text-2xl font-extrabold text-white">{value}</div><div className="text-xs font-semibold text-slate-200">{label}</div></div>}
function FilterChip({label,onClear}:{label:string;onClear:()=>void}){return <button type="button" onClick={onClear} className="filter-chip">{label} ×</button>}
function PartySummary({label,value,active,onClick}:{label:string;value:number;active:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} className={`rounded-card border p-4 text-left transition ${active?'border-primary bg-primary-light shadow-card':'border-border bg-card hover:border-primary'}`}><div className="text-2xl font-extrabold text-navy">{value.toLocaleString()}</div><div className="mt-1 text-sm font-bold text-body">{label}</div></button>}
function ResidentPhoto({resident,large=false}:{resident:Resident;large?:boolean}){const initials=(resident.name||'?').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();const size=large?'h-16 w-16':'h-12 w-12';return resident.photo_url?<img src={resident.photo_url} alt="Resident" className={`${size} shrink-0 rounded-card border border-border object-cover`} loading="lazy"/>:<div className={`grid ${size} shrink-0 place-items-center rounded-card bg-primary-light text-xs font-extrabold text-primary`}>{initials}</div>}
function PartyBadge({party}:{party?:string|null}){if(!party)return <span className="text-body">—</span>;const key=party.toUpperCase();const cls=key==='PNC'?'bg-teal-50 text-teal-700 ring-teal-200':key==='MDP'?'bg-yellow-50 text-yellow-800 ring-yellow-200':'bg-slate-50 text-slate-700 ring-slate-200';return <span className={`inline-flex rounded-pill px-2.5 py-1 text-xs font-bold ring-1 ${cls}`}>{party}</span>}