'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {getSharedAssignmentProgress,getSharedResidents,getWorkflowShare,submitSharedAssignments} from '../lib/operations';
import type {SharedAssignmentRecord,WorkflowShare} from '../lib/operations';
import type {Resident} from '../lib/types';

export default function WorkflowShareContent(){
 const token=useSearchParams().get('token')||'';
 const [rows,setRows]=useState<Resident[]>([]),[share,setShare]=useState<WorkflowShare|null>(null),[progress,setProgress]=useState<SharedAssignmentRecord[]>([]),[title,setTitle]=useState('Shared worklist'),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[name,setName]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<Set<string>>(new Set());
 async function load(){if(!token){setError('Missing share token.');setLoading(false);return}try{const item=await getWorkflowShare(token);setShare(item);setTitle(item.title||'Shared worklist');const [residentRows,assignmentRows]=await Promise.all([getSharedResidents(item),getSharedAssignmentProgress(item)]);setRows(residentRows);setProgress(assignmentRows)}catch(e){setError(e instanceof Error?e.message:'Unable to load share link')}finally{setLoading(false)}}
 useEffect(()=>{load()},[token]);
 const assignedMap=useMemo(()=>new Map(progress.map(item=>[String(item.resident_id),item])),[progress]);
 const availableRows=useMemo(()=>rows.filter(r=>!assignedMap.has(String(r.id))),[rows,assignedMap]);
 const visible=useMemo(()=>rows.filter(r=>[r.name,r.national_id,r.phone,r.house,r.lives_in,r.election_box].join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const visibleAvailable=useMemo(()=>visible.filter(r=>!assignedMap.has(String(r.id))),[visible,assignedMap]);
 const assignmentMode=share?.workflow==='assignments'&&share.can_update;
 const grouped=useMemo(()=>{const map=new Map<string,number>();progress.forEach(item=>map.set(item.assignee_name,(map.get(item.assignee_name)||0)+1));return [...map.entries()].sort((a,b)=>b[1]-a[1])},[progress]);
 function toggle(id:string){if(assignedMap.has(id))return;setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 function toggleVisible(){setSelected(current=>{const next=new Set(current);const ids=visibleAvailable.map(r=>String(r.id));const allSelected=ids.length>0&&ids.every(id=>next.has(id));ids.forEach(id=>allSelected?next.delete(id):next.add(id));return next})}
 async function submit(){if(!share)return;setSubmitting(true);setError('');setSuccess('');try{const count=await submitSharedAssignments(share,name,[...selected]);setSuccess(`${count} resident${count===1?'':'s'} assigned successfully to ${name.trim()}.`);setSelected(new Set());await load()}catch(e){setError(e instanceof Error?e.message:'Unable to submit assignments')}finally{setSubmitting(false)}}
 if(loading)return <main className="mx-auto max-w-6xl p-5"><div className="h-40 animate-pulse rounded-2xl bg-primary-light"/></main>;
 return <main className="mx-auto max-w-6xl space-y-4 p-4 sm:p-6">
  <header className="page-hero"><p className="eyebrow">Restricted campaign worklist</p><h1 className="mt-2">{title}</h1><p className="mt-2 text-sm text-body">This link shows only the resident information required for assignment.</p></header>
  {error&&<div className="error-banner">{error}</div>}
  {success&&<div className="info-banner"><div><b className="text-navy">Assignment submitted</b><p className="mt-1">{success}</p></div></div>}
  {!error&&assignmentMode&&<section className="grid gap-3 sm:grid-cols-3"><div className="metric-card"><span className="eyebrow">Total shared</span><strong className="mt-2 block text-3xl text-navy">{rows.length}</strong></div><div className="metric-card"><span className="eyebrow">Already assigned</span><strong className="mt-2 block text-3xl text-navy">{progress.length}</strong></div><div className="metric-card"><span className="eyebrow">Still available</span><strong className="mt-2 block text-3xl text-navy">{availableRows.length}</strong></div></section>}
  {!error&&assignmentMode&&grouped.length>0&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">Submission progress</p><h2 className="mt-1">Who has already submitted</h2></div></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{grouped.map(([person,count])=><div key={person} className="soft-card"><b className="text-navy">{person}</b><p className="mt-1 text-sm text-body">{count} resident{count===1?'':'s'} assigned</p></div>)}</div></section>}
  {!error&&assignmentMode&&<section className="panel"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><div><label className="field-label">Your name</label><input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name"/></div><div><label className="field-label">Search residents</label><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, ID, mobile, address or box"/></div><div className="flex items-end"><button className="btn-secondary w-full" disabled={!visibleAvailable.length} onClick={toggleVisible}>{visibleAvailable.length&&visibleAvailable.every(r=>selected.has(String(r.id)))?'Unselect visible':'Select available'}</button></div></div><div className="mt-4 flex flex-col gap-3 rounded-xl border border-border bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-navy">{selected.size} selected</b><p className="mt-1 text-xs text-body">Already assigned residents are locked and cannot be submitted again.</p></div><button className="btn-primary" disabled={submitting||!name.trim()||!selected.size} onClick={submit}>{submitting?'Submitting…':'Submit assignments'}</button></div></section>}
  {!error&&<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visible.map(r=>{const id=String(r.id),checked=selected.has(id),assigned=assignedMap.get(id);return <article key={id} className={`soft-card ${assignmentMode&&!assigned?'cursor-pointer':''} ${checked?'ring-2 ring-primary':''} ${assigned?'opacity-75':''}`} onClick={()=>assignmentMode&&!assigned&&toggle(id)}>{assignmentMode&&<div className="mb-3 flex items-center justify-between"><span className="eyebrow">Resident ID {id}</span>{assigned?<span className="status-chip bg-emerald-50 text-emerald-700">Assigned</span>:<input type="checkbox" checked={checked} onChange={()=>toggle(id)} onClick={e=>e.stopPropagation()} className="h-5 w-5" aria-label={`Select ${r.name||id}`}/>}</div>}<h2 className="text-base">{r.name||'Unnamed resident'}</h2>{assigned&&<div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm"><b className="text-emerald-800">Assigned to {assigned.assignee_name}</b><p className="mt-1 text-xs text-emerald-700">{assigned.assigned_at?new Date(assigned.assigned_at).toLocaleString():'Submission recorded'}</p></div>}<dl className="mt-4 grid gap-2 text-sm"><Info label="National ID" value={r.national_id}/><Info label="Mobile" value={r.phone}/><Info label="Official address" value={r.house}/><Info label="Living place" value={r.lives_in}/><Info label="Election box" value={r.election_box}/></dl></article>})}</section>}
  {!error&&!visible.length&&<div className="empty-state">No residents match this shared worklist.</div>}
 </main>
}
function Info({label,value}:{label:string;value?:string|null}){return <div className="flex justify-between gap-3 border-b border-border pb-2"><dt className="text-body">{label}</dt><dd className="text-right font-semibold text-navy">{value||'—'}</dd></div>}