'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {getSharedAssignmentProgress,getSharedResidents,getWorkflowShare,submitSharedAssignments} from '../lib/operations';
import type {SharedAssignmentRecord,WorkflowShare} from '../lib/operations';
import type {Resident} from '../lib/types';
import {ResidentIdentity} from '../shared/ResidentIdentity';

export default function WorkflowShareContent(){
 const token=useSearchParams().get('token')||'';
 const [rows,setRows]=useState<Resident[]>([]),[share,setShare]=useState<WorkflowShare|null>(null),[progress,setProgress]=useState<SharedAssignmentRecord[]>([]),[title,setTitle]=useState('Shared worklist'),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<Set<string>>(new Set());
 async function load(){if(!token){setError('Missing share token.');setLoading(false);return}try{const item=await getWorkflowShare(token);setShare(item);setTitle(item.title||'Shared worklist');const [residentRows,assignmentRows]=await Promise.all([getSharedResidents(item),getSharedAssignmentProgress(item)]);setRows(residentRows);setProgress(assignmentRows)}catch(e){setError(e instanceof Error?e.message:'Unable to load share link')}finally{setLoading(false)}}
 useEffect(()=>{load()},[token]);
 const assignmentMode=share?.workflow==='assignments'&&share.can_update;
 const assigneeName=(share?.status_filter||'').trim();
 const ownProgress=useMemo(()=>progress.filter(item=>item.assignee_name.trim().toLowerCase()===assigneeName.toLowerCase()),[progress,assigneeName]);
 const ownAssignedIds=useMemo(()=>new Set(ownProgress.map(item=>String(item.resident_id))),[ownProgress]);
 const visible=useMemo(()=>rows.filter(r=>[r.name,r.national_id,r.phone,r.house,r.lives_in,r.election_box].join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const visibleSelectable=useMemo(()=>visible.filter(r=>!ownAssignedIds.has(String(r.id))),[visible,ownAssignedIds]);
 const selectedRows=useMemo(()=>rows.filter(r=>selected.has(String(r.id))),[rows,selected]);
 function toggle(id:string){if(ownAssignedIds.has(id))return;setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 function toggleVisible(){setSelected(current=>{const next=new Set(current);const ids=visibleSelectable.map(r=>String(r.id));const allSelected=ids.length>0&&ids.every(id=>next.has(id));ids.forEach(id=>allSelected?next.delete(id):next.add(id));return next})}
 async function submit(){if(!share)return;if(!assigneeName){setError('This assignment link has no assignee name. Ask the sender to create a new link.');return}setSubmitting(true);setError('');setSuccess('');try{const count=await submitSharedAssignments(share,assigneeName,[...selected]);setSuccess(`${count} resident${count===1?'':'s'} submitted successfully for ${assigneeName}.`);setSelected(new Set());await load()}catch(e){setError(e instanceof Error?e.message:'Unable to submit assignments')}finally{setSubmitting(false)}}
 if(loading)return <main className="mx-auto max-w-6xl p-5"><div className="h-40 animate-pulse rounded-2xl bg-primary-light"/></main>;
 return <main className="mx-auto max-w-6xl space-y-4 p-4 sm:p-6">
  <header className="page-hero"><p className="eyebrow">Private assignment worklist</p><h1 className="mt-2">{title}</h1><div className="mt-4 inline-flex rounded-full bg-primary-light px-4 py-2 text-sm font-bold text-primary">Assigned to: {assigneeName||'Name missing'}</div><p className="mt-3 text-sm text-body">Your selections are private. You will not see selections made by other assignees.</p></header>
  {error&&<div className="error-banner">{error}</div>}
  {success&&<div className="info-banner"><div><b className="text-navy">Assignment submitted</b><p className="mt-1">{success}</p></div></div>}
  {!error&&assignmentMode&&<section className="grid gap-3 sm:grid-cols-3"><div className="metric-card"><span className="eyebrow">Residents in your link</span><strong className="mt-2 block text-3xl text-navy">{rows.length}</strong></div><div className="metric-card"><span className="eyebrow">You already selected</span><strong className="mt-2 block text-3xl text-navy">{ownProgress.length}</strong></div><div className="metric-card"><span className="eyebrow">Available for you</span><strong className="mt-2 block text-3xl text-navy">{Math.max(0,rows.length-ownProgress.length)}</strong></div></section>}
  {!error&&assignmentMode&&<section className="panel"><div className="grid gap-3 md:grid-cols-[1fr_auto]"><div><label className="field-label">Search residents</label><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, ID, mobile, address or box"/></div><div className="flex items-end"><button className="btn-secondary w-full" disabled={!visibleSelectable.length} onClick={toggleVisible}>{visibleSelectable.length&&visibleSelectable.every(r=>selected.has(String(r.id)))?'Unselect visible':'Select visible'}</button></div></div><div className="mt-4 rounded-xl border border-border bg-slate-50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-navy">{selected.size} selected for {assigneeName}</b><p className="mt-1 text-xs text-body">Review the selected residents below before submitting.</p></div><button className="btn-primary" disabled={submitting||!assigneeName||!selected.size} onClick={submit}>{submitting?'Submitting…':'Confirm and submit'}</button></div>{selectedRows.length>0&&<div className="mt-4 grid gap-3 sm:grid-cols-2">{selectedRows.map(r=><article key={String(r.id)} className="soft-card"><div className="flex items-start justify-between gap-3"><ResidentIdentity resident={r}/><button className="btn-ghost min-h-8 px-2 text-xs" onClick={()=>toggle(String(r.id))}>Remove</button></div><dl className="mt-4 grid gap-2 text-sm"><Info label="Resident ID" value={String(r.id)}/><Info label="Mobile" value={r.phone}/><Info label="Official address" value={r.house}/><Info label="Election box" value={r.election_box}/></dl></article>)}</div>}</div></section>}
  {!error&&<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visible.map(r=>{const id=String(r.id),checked=selected.has(id),alreadySelected=ownAssignedIds.has(id);return <article key={id} className={`soft-card ${assignmentMode&&!alreadySelected?'cursor-pointer':''} ${checked?'ring-2 ring-primary':''}`} onClick={()=>assignmentMode&&!alreadySelected&&toggle(id)}><div className="mb-4 flex items-start justify-between gap-3"><ResidentIdentity resident={r}/>{assignmentMode&&(alreadySelected?<span className="status-chip shrink-0 bg-emerald-50 text-emerald-700">You selected</span>:<input type="checkbox" checked={checked} onChange={()=>toggle(id)} onClick={e=>e.stopPropagation()} className="h-5 w-5 shrink-0" aria-label={`Select ${r.name||id}`}/>)}</div><dl className="grid gap-2 text-sm"><Info label="Resident ID" value={id}/><Info label="National ID" value={r.national_id}/><Info label="Mobile" value={r.phone}/><Info label="Official address" value={r.house}/><Info label="Living place" value={r.lives_in}/><Info label="Election box" value={r.election_box}/></dl></article>})}</section>}
  {!error&&!visible.length&&<div className="empty-state">No residents match this shared worklist.</div>}
 </main>
}
function Info({label,value}:{label:string;value?:string|null}){return <div className="flex justify-between gap-3 border-b border-border pb-2"><dt className="text-body">{label}</dt><dd className="text-right font-semibold text-navy">{value||'—'}</dd></div>}
